In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import pandas_profiling
import statistics

In [2]:
pd.set_option('display.max_columns', None)

# Importing data

As a start, let's import the data from kaggle and and clean it up before we look into other possible sources of data

In [3]:
ls data

OECD_life_expectancy_2000_2019.csv
gap_minder/
gap_minder_child_mortality_0_5_year_olds_dying_per_1000_born.csv
kaggle_life_expectancy_data.csv
kaggle_life_expectancy_data.xlsx

In [4]:
df0 = pd.read_csv("data/kaggle_life_expectancy_data.csv")

In [5]:
df0.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [6]:
df0 = df0.rename(columns={column:column.lower().replace(" ", "_") for column in df0.columns}) #reformat column names

In [7]:
df0.head()

,country,year,status,life_expectancy_,adult_mortality,infant_deaths,alcohol,percentage_expenditure,hepatitis_b,measles_,_bmi_,under-five_deaths_,polio,total_expenditure,diphtheria_,_hiv/aids,gdp,population,_thinness__1-19_years,_thinness_5-9_years,income_composition_of_resources,schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [8]:
#apparently there were some spaces in the columns names. 
#Let's fix this now by removing all the '_' from the beginnings and endings of columns names

In [9]:
df0.columns

Index(['country', 'year', 'status', 'life_expectancy_', 'adult_mortality',
       'infant_deaths', 'alcohol', 'percentage_expenditure', 'hepatitis_b',
       'measles_', '_bmi_', 'under-five_deaths_', 'polio', 'total_expenditure',
       'diphtheria_', '_hiv/aids', 'gdp', 'population',
       '_thinness__1-19_years', '_thinness_5-9_years',
       'income_composition_of_resources', 'schooling'],
      dtype='object')

In [10]:
cols = ['country', 'year', 'status', 'life_expectancy_', 'adult_mortality',
       'infant_deaths', 'alcohol', 'percentage_expenditure', 'hepatitis_b',
       'measles_', '_bmi_', 'under-five_deaths_', 'polio', 'total_expenditure',
       'diphtheria_', '_hiv/aids', 'gdp', 'population',
       '_thinness__1-19_years', '_thinness_5-9_years',
       'income_composition_of_resources', 'schooling']

In [11]:

for i in range(0,len(cols)):
    if cols[i][0] == "_":
        cols[i] = cols[i][1:] #remove left "_"
    if cols[i][len(cols[i])-1] == "_":
        cols[i] = cols[i][:-1] #remove right "_"

In [12]:
print(cols) #check

['country', 'year', 'status', 'life_expectancy', 'adult_mortality', 'infant_deaths', 'alcohol', 'percentage_expenditure', 'hepatitis_b', 'measles', 'bmi', 'under-five_deaths', 'polio', 'total_expenditure', 'diphtheria', 'hiv/aids', 'gdp', 'population', 'thinness__1-19_years', 'thinness_5-9_years', 'income_composition_of_resources', 'schooling']

In [13]:
df0.columns = cols #renaming columns

In [14]:
df0.head()

,country,year,status,life_expectancy,adult_mortality,infant_deaths,alcohol,percentage_expenditure,hepatitis_b,measles,bmi,under-five_deaths,polio,total_expenditure,diphtheria,hiv/aids,gdp,population,thinness__1-19_years,thinness_5-9_years,income_composition_of_resources,schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [15]:
#let's also turn everything else into lower case
df0 = df0.applymap(lambda s:s.lower() if type(s) == str else s)

In [147]:
df0.shape

(2938, 22)

In [16]:
#let's also display as a markdown the description of each column provided on kaggle


|Field|Description|
|---:|:---|
|Country|Country|
|Year|Year|
|Status|Developed or Developing status|
|Life expectancy|Life Expectancy in age|
|Adult Mortality|Adult Mortality Rates of both sexes (probability of dying between 15 and 60 years per 1000 population)|
|infant deaths|Number of Infant Deaths per 1000 population|
|Alcohol|Alcohol, recorded per capita (15+) consumption (in litres of pure alcohol)|
|percentage expenditure|Expenditure on health as a percene of Gross Domestic Product per capita(%)|
|Hepatitis B|Hepatitis B (HepB) immunization coverage among 1-year-olds (%)|
|Measles|Measles - number of reported cases per 1000 population|
|BMI|Average Body Mass Index of entire population|
|under-five deaths|Number of under-five deaths per 1000 population|
|Polio|Polio (Pol3) immunization coverage among 1-year-olds (%)|
|Total expenditure|General government expenditure on health as a percene of total government expenditure (%)|
|Diphtheria|Diphtheria tetanus toxoid and pertussis (DTP3) immunization coverage among 1-year-olds (%)|
|HIV/AIDS|Deaths per 1 000 live births HIV/AIDS (0-4 years)|
|GDP|Gross Domestic Product per capita (in USD)|
|Population|Population of the country|
|thinness 1-19 years|Prevalence of thinness among children and adolescents for Age 10 to 19 (%)|
|thinness 5-9 years|Prevalence of thinness among children for Age 5 to 9(%)|
|Income composition of resources|Income composition of resources|
|Schooling|Number of years of Schooling(years)|

In [17]:
# the data desctiption above isn't really clear, e.g.:
# the income composition of resources doesn't make sense
# health data is not consistent, hepatitis B is for immunization, Measles is for reported cases
# just by looking at the first 5 rows, we can see the there are some massive inconsistencies in the data: e.g. "percentage expenditure", "gdp", "population"
# also, how can the value for measles be > 1000?

In [18]:
df0.describe()

,year,life_expectancy,adult_mortality,infant_deaths,alcohol,percentage_expenditure,hepatitis_b,measles,bmi,under-five_deaths,polio,total_expenditure,diphtheria,hiv/aids,gdp,population,thinness__1-19_years,thinness_5-9_years,income_composition_of_resources,schooling
count,2938.000000,2928.000000,2928.000000,2938.000000,2744.000000,2938.000000,2385.000000,2938.000000,2904.000000,2938.000000,2919.000000,2712.00000,2919.000000,2938.000000,2490.000000,2.286000e+03,2904.000000,2904.000000,2771.000000,2775.000000
mean,2007.518720,69.224932,164.796448,30.303948,4.602861,738.251295,80.940461,2419.592240,38.321247,42.035739,82.550188,5.93819,82.324084,1.742103,7483.158469,1.275338e+07,4.839704,4.870317,0.627551,11.992793
std,4.613841,9.523867,124.292079,117.926501,4.052413,1987.914858,25.070016,11467.272489,20.044034,160.445548,23.428046,2.49832,23.716912,5.077785,14270.169342,6.101210e+07,4.420195,4.508882,0.210904,3.358920
min,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.37000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000
25%,2004.000000,63.100000,74.000000,0.000000,0.877500,4.685343,77.000000,0.000000,19.300000,0.000000,78.000000,4.26000,78.000000,0.100000,463.935626,1.957932e+05,1.600000,1.500000,0.493000,10.100000
50%,2008.000000,72.100000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.75500,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000
75%,2012.000000,75.700000,228.000000,22.000000,7.702500,441.534144,97.000000,360.250000,56.200000,28.000000,97.000000,7.49250,97.000000,0.800000,5910.806335,7.420359e+06,7.200000,7.200000,0.779000,14.300000
max,2015.000000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.60000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000

In [19]:
# we can already see by comparing the mean and the std that there some major inconsistencies in the data
# let's also check null values:
df0.isna().sum()

country                              0
year                                 0
status                               0
life_expectancy                     10
adult_mortality                     10
infant_deaths                        0
alcohol                            194
percentage_expenditure               0
hepatitis_b                        553
measles                              0
bmi                                 34
under-five_deaths                    0
polio                               19
total_expenditure                  226
diphtheria                          19
hiv/aids                             0
gdp                                448
population                         652
thinness__1-19_years                34
thinness_5-9_years                  34
income_composition_of_resources    167
schooling                          163
dtype: int64

In [20]:
#before we do anything with null values, let's check if the non-null values make sense
#for this, let's provisionally drop all null values to check out the rest
df0_no_null = df0.dropna(how='any',axis=0)

In [21]:
df0_no_null

,country,year,status,life_expectancy,adult_mortality,infant_deaths,alcohol,percentage_expenditure,hepatitis_b,measles,bmi,under-five_deaths,polio,total_expenditure,diphtheria,hiv/aids,gdp,population,thinness__1-19_years,thinness_5-9_years,income_composition_of_resources,schooling
0,afghanistan,2015,developing,65.0,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,afghanistan,2014,developing,59.9,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,afghanistan,2013,developing,59.9,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,afghanistan,2012,developing,59.5,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,afghanistan,2011,developing,59.2,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,zimbabwe,2004,developing,44.3,723.0,27,4.36,0.000000,68.0,31,27.1,42,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,zimbabwe,2003,developing,44.5,715.0,26,4.06,0.000000,7.0,998,26.7,41,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,zimbabwe,2002,developing,44.8,73.0,25,4.43,0.000000,73.0,304,26.3,40,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,zimbabwe,2001,developing,45.3,686.0,25,1.72,0.000000,76.0,529,25.9,39,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,zimbabwe,2000,developing,46.0,665.0,24,1.68,0.000000,79.0,1483,25.5,39,78.0,7.10,78.0,43.5,547.358879,12222251.0,11.0,11.2,0.434,9.8

In [22]:
#for the sake of this test, let's drop the "year" and "status columns"
df0_test = df0_no_null.drop(columns = ["year","status"])

In [23]:
df0_test.columns

Index(['country', 'life_expectancy', 'adult_mortality', 'infant_deaths',
       'alcohol', 'percentage_expenditure', 'hepatitis_b', 'measles', 'bmi',
       'under-five_deaths', 'polio', 'total_expenditure', 'diphtheria',
       'hiv/aids', 'gdp', 'population', 'thinness__1-19_years',
       'thinness_5-9_years', 'income_composition_of_resources', 'schooling'],
      dtype='object')

In [24]:
#let's create an empty dataframe that we will populate with the results of our tests
cols2 = ['country', 'life_expectancy', 'adult_mortality', 'infant_deaths',
       'alcohol', 'percentage_expenditure', 'hepatitis_b', 'measles', 'bmi',
       'under-five_deaths', 'polio', 'total_expenditure', 'diphtheria',
       'hiv/aids', 'gdp', 'population', 'thinness__1-19_years',
       'thinness_5-9_years', 'income_composition_of_resources', 'schooling']
df0_test_results = pd.DataFrame(columns = cols2)

In [25]:
df0_test_results

Empty DataFrame
Columns: [country, life_expectancy, adult_mortality, infant_deaths, alcohol, percentage_expenditure, hepatitis_b, measles, bmi, under-five_deaths, polio, total_expenditure, diphtheria, hiv/aids, gdp, population, thinness__1-19_years, thinness_5-9_years, income_composition_of_resources, schooling]
Index: []

In [26]:
#let's fill out the first column with unique country values:
df0_test_results["country"] = list(set(list(df0_test["country"])))

In [27]:
df0_test_results

,country,life_expectancy,adult_mortality,infant_deaths,alcohol,percentage_expenditure,hepatitis_b,measles,bmi,under-five_deaths,polio,total_expenditure,diphtheria,hiv/aids,gdp,population,thinness__1-19_years,thinness_5-9_years,income_composition_of_resources,schooling
0,tonga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,azerbaijan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,rwanda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,morocco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,uzbekistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,panama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,greece,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,malaysia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,sri lanka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
# now let's fill out this dataframe with the values we want to test
# the idea here is for each country, to identify if there is any brutal variation in the value over the years observed
# which most likely indicates inaccuracy in the data: let's look at something very simple: "(maximum value - minimum value)/mean"

In [29]:
df0_test_results.columns

Index(['country', 'life_expectancy', 'adult_mortality', 'infant_deaths',
       'alcohol', 'percentage_expenditure', 'hepatitis_b', 'measles', 'bmi',
       'under-five_deaths', 'polio', 'total_expenditure', 'diphtheria',
       'hiv/aids', 'gdp', 'population', 'thinness__1-19_years',
       'thinness_5-9_years', 'income_composition_of_resources', 'schooling'],
      dtype='object')

In [30]:
l0 = ['life_expectancy', 'adult_mortality', 'infant_deaths',
       'alcohol', 'percentage_expenditure', 'hepatitis_b', 'measles', 'bmi',
       'under-five_deaths', 'polio', 'total_expenditure', 'diphtheria',
       'hiv/aids', 'gdp', 'population', 'thinness__1-19_years',
       'thinness_5-9_years', 'income_composition_of_resources', 'schooling'] #define iterable list with all column names except first one

In [31]:
for j in range (0, len(df0_test_results["country"])):
    for i in range (0,len(l0)):
        A = df0_no_null.loc[df0_no_null["country"] == df0_test_results["country"][j]] #this is a dataframe which is an extract from df0_no_null containing all rows for a given country. the j variable iterates through all unique countries.
        m = min(A[l0[i]].tolist()) 
        M = max(A[l0[i]].tolist())
        avg = statistics.mean (A[l0[i]].tolist()) # for each row "j" in df0_test_results, i.e. for each country, we want to append each column with the value we are looking for ((M-m)/avg) by looping through all the columns of the provisionary dataframe "A"
             
        if avg != 0:
            df0_test_results.loc[j,l0[i]] = (M-m)/avg
        else:
            df0_test_results.loc[j,l0[i]] = 0 #the conditional statement is just to avoid dividing by 0 when avg = 0

In [32]:
df0_test_results

,country,life_expectancy,adult_mortality,infant_deaths,alcohol,percentage_expenditure,hepatitis_b,measles,bmi,under-five_deaths,polio,total_expenditure,diphtheria,hiv/aids,gdp,population,thinness__1-19_years,thinness_5-9_years,income_composition_of_resources,schooling
0,tonga,0.0234591,1.11283,0,1.74757,1.98369,1.12832,15,1.08971,0,1.00655,0.386093,1.18911,0,2.03231,3.65414,0,0,0.0630794,0.0984991
1,azerbaijan,0.143367,1.24326,0.346667,2.01822,1.87871,1.57844,6.44008,1.05742,0.443182,1.20145,0.606917,0.231273,0,1.93421,4.87253,0.104558,0.102632,0.142609,0.140162
2,rwanda,0.264631,1.78307,0.972441,1.51053,3.32455,0.114767,6.96374,1.20511,1.14212,0.147727,1.09358,0.114767,1.86059,1.97758,3.09775,0.213115,0.242991,0.340253,0.377115
3,morocco,0.116645,1.51261,0.415385,0.366324,1.72285,1.04086,3.92117,1.07798,0.436508,0.0826446,0.361955,0.0824176,0,1.56785,1.55481,0.0619195,0.0632911,0.208071,0.403279
4,uzbekistan,0.0308614,0.0487703,0.514388,1.74571,2.95114,0.387903,3.49393,1.17326,0.561728,0.0507812,0.242432,0.0305164,1.34483,2.75484,2.93311,0.0962963,0.0634146,0.140002,0.0935252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,zimbabwe,0.301701,1.52082,0.260546,1.07541,4.26309,1.29559,9.84832,1.13391,0.289855,1.17647,0.431912,1.1828,1.52459,2.08681,2.03699,1.37899,1.39699,0.211689,0.122532
129,panama,0.0274689,0.996904,0.933333,0.242922,2.8203,1.13821,14,1.05822,0.583333,1.07601,0.335523,1.14878,0.823529,2.31367,1.8011,0.193103,0.248227,0.0788845,0.0468489
130,greece,0.12064,1.03074,5,0.282847,1.89749,1.00603,5.62972,1.02304,2.14286,0.989736,0.24008,0.103663,0,1.75352,6.76435,0.122951,0.136364,0.0808754,0.208158
131,malaysia,0.0325762,1.14994,0.306122,0.244565,2.68247,0.0313152,4.18156,1.16209,0.241935,0.04158,0.242753,0.0415512,0,2.40549,2.34966,0.253262,0.259434,0.0910796,0.111762
132,sri lanka,0.076225,0.386463,0.782609,0.660922,2.7355,0.745134,6.04302,1.1587,1.5,0.020339,0.369845,0.0203218,0,3.10834,1.89376,0.0130435,0.0325733,0.0861342,0.0975

In [33]:
with pd.option_context("display.max_rows", None): display(df0_test_results) #let's look at all the rows here

,country,life_expectancy,adult_mortality,infant_deaths,alcohol,percentage_expenditure,hepatitis_b,measles,bmi,under-five_deaths,polio,total_expenditure,diphtheria,hiv/aids,gdp,population,thinness__1-19_years,thinness_5-9_years,income_composition_of_resources,schooling
0,tonga,0.0234591,1.11283,0,1.74757,1.98369,1.12832,15,1.08971,0,1.00655,0.386093,1.18911,0,2.03231,3.65414,0,0,0.0630794,0.0984991
1,azerbaijan,0.143367,1.24326,0.346667,2.01822,1.87871,1.57844,6.44008,1.05742,0.443182,1.20145,0.606917,0.231273,0,1.93421,4.87253,0.104558,0.102632,0.142609,0.140162
2,rwanda,0.264631,1.78307,0.972441,1.51053,3.32455,0.114767,6.96374,1.20511,1.14212,0.147727,1.09358,0.114767,1.86059,1.97758,3.09775,0.213115,0.242991,0.340253,0.377115
3,morocco,0.116645,1.51261,0.415385,0.366324,1.72285,1.04086,3.92117,1.07798,0.436508,0.0826446,0.361955,0.0824176,0,1.56785,1.55481,0.0619195,0.0632911,0.208071,0.403279
4,uzbekistan,0.0308614,0.0487703,0.514388,1.74571,2.95114,0.387903,3.49393,1.17326,0.561728,0.0507812,0.242432,0.0305164,1.34483,2.75484,2.93311,0.0962963,0.0634146,0.140002,0.0935252
5,luxembourg,0.126394,1.34086,0,0.177823,2.14317,0.195087,6.66667,1.14008,0,0.0306122,0.194771,0.0101078,0,2.07226,1.97718,0.105634,0.109489,0.0524555,0.0367107
6,mongolia,0.0852446,1.16597,0.625,2.45964,1.91899,0.0616438,12.4065,1.20719,1,0.0512996,0.38026,0.0514051,0,2.22217,1.35104,0.174927,0.125348,0.223631,0.470995
7,nigeria,0.185466,1.15226,0.126026,1.18625,2.09759,1.06383,5.03384,1.1067,0.162346,1.31579,0.305403,1.35011,0.315789,1.87033,3.03633,1.34091,1.34328,0.118174,0.116897
8,ghana,0.185994,1.3636,0.124283,1.44354,2.42612,1.36523,8.79823,1.10592,0.150773,1.11133,0.492205,1.26214,1.21875,2.03739,2.55497,0.318367,0.335397,0.173989,0.426059
9,armenia,0.0354674,1.10795,0,0.375405,2.09473,0.459067,7.85649,1.11296,0,0.992481,0.52249,0.989264,0,1.87485,2.80013,0.0491803,0.0474684,0.143775,0.162024
10,lesotho,0.160466,1.13859,0.226415,1.46851,1.84092,1.25728,8.80708,1.17153,0.162162,1.23741,1.3158,1.11897,1.16963,1.33572,1.94747,1.19578,1.23593,0.118248,0.0555985
11,ireland,0.0599233,1.11913,0,0.12338,1.55914,0.575117,2.23069,1.11871,0,0.0210084,0.119192,0.0210084,0,1.46882,1.10459,0,0,0.0165819,0.021645
12,paraguay,0.0302025,1.04378,0.324324,1.24683,2.19931,1.02154,0,0.178775,0.285714,1.10656,1.28485,0.144578,0.705882,2.01336,1.73084,0.186047,0.192771,0.0741862,0.0653951
13,mauritius,0.0440852,0.194253,0,1.57913,2.03979,0.114424,13.412,1.16109,0,0.114108,0.333726,0.114266,0.9375,1.91198,1.7985,0.146536,0.161002,0.14189,0.193741
14,bulgaria,0.0439923,1.19455,0,0.218125,2.29845,0.084507,13.4801,1.09389,0,0.0952717,0.280542,0.0849257,0,1.60017,1.50259,0.279503,0.275229,0.103705,0.139296
15,botswana,0.344724,1.50998,0,1.40257,1.87305,0.990783,10.5307,1.06067,0.625,0.010395,0.332083,0.0208623,2.0881,1.73463,1.78269,1.50533,1.36249,0.222092,0.0743392
16,samoa,0.10327,1.18539,0,1.53846,2.49327,1.51829,13.3333,1.07856,0,1.54386,0.520155,1.09989,0,2.05386,1.34919,0,0.576923,0.0901211,0.0712777
17,honduras,0.0480198,1.12235,0.633803,0.203813,1.69922,0.0632022,0,1.15148,0.689655,0.115465,0.38663,0.0628053,1.64062,1.56391,2.89532,0.289256,0.254958,0.113958,0.174847
18,benin,0.0710477,0.12625,0,1.46079,2.15894,1.22796,2.38019,1.19689,0.0255403,1.13176,0.251363,1.14571,0.585586,1.54056,2.21815,0.270066,0.286398,0.1539,0.374894
19,peru,0.0433066,1.18625,0.646154,1.25516,1.86788,0.333642,12,1.13795,0.650602,0.334615,0.202874,0.199078,1.125,1.79476,1.94473,0.169014,0.169014,0.0707714,0.0453686
20,djibouti,0.146672,0.161765,0,0.325203,1.5943,0.828479,5.62698,1.04631,0.533333,0.129032,0.979935,0.129032,0.584475,1.5943,1.35754,0.0353982,0.0541761,0.114542,0.31929
21,uruguay,0.0249956,0.166389,1.66667,0.267307,3.49326,0.053041,0,1.09798,1.25,0.0530786,0.579429,0.980466,0,2.53146,1.46752,0.186722,0.193133,0.0693959,0.111744
22,chad,0.14153,1.1082,0,1.35692,1.60993,1.26943,5.62134,0.131429,0.0252708,1.50673,0.218848,1.25641,0.47191,1.27034,1.61729,0.11938,0.131868,0.141689,0.191176
23,dominican republic,0.0595238,1.38526,0.154639,0.235463,2.81649,1.26431,10.3125,1.10697,0.254237,1.05521,0.380234,0.228732,1.47321,1.88097,2.1289,0.143678,0.147638,0.089338,0.0786576
24,bosnia and herzegovina,0.0288783,1.5422,0,0.245604,2.72214,1.2018,9.87728,1.02661,0,1.14389,0.180738,1.04762,0,2.31828,2.08272,0.222973,0.225256,1.26366,0.143347
25,serbia,0.032349,0.100492,0,0.264313,1.5299,0.375879,6.29057,0.108173,0,0.0737548,1.54454,0.107212,0,1.49351,2.01099,0.217391,0.214844,0.0679918,0.0881175
26,papua new guinea,0.147727,1.15038,0.09375,1.49828,2.44014,1.18935,7.03674,1.0803,0.144231,1.18123,0.807298,0.352595,0.662983,2.77687,1.67031,0.212264,0.146341,0.200893,0.449882
27,nicaragua,0.068157,1.10681,0.638298,0.130677,2.40436,0.207726,0,1.14486,0.526316,1.0404,0.615095,0.207726,1.28571,1.96033,2.79081,0.20202,0.212014,0.123142,0.135461
28,netherlands,0.00737781,1.20635,0,1.35431,0.343329,2.44898,3.70208,1.16614,0,0.0103359,1.52256,0.0103359,0,1.18069,3.27188,0,0,0.0130541,0.0503497
29,uganda,0.322036,1.84411,0.502636,1.3571,2.06819,1.18765,6.07123,0.287328,0.623644,1.14169,0.453462,1.12778,0.912281,1.62769,2.26377,0.1772,0.193548,0.175286,0.149748
30,syrian arab republic,0.0164018,0.115163,0.222222,0.521935,1.43057,1.18343,1.60786,0.118248,0.285714,0.0356612,0.311198,1.38813,0,1.48367,1.94757,0.0609524,0.0626223,0.0916905,0.141011
31,sweden,0.00732601,0.0707965,0,0.0136054,1.66838,0.436681,0.75188,0.0222889,0,0,0.0227848,0,0,1.66525,1.88135,0.0701754,0,0.00553403,0.0126183
32,cyprus,0.0617751,1.16093,0,1.26892,2.35465,0.0866426,8.70968,0.124363,0,0.0203943,0.261834,0.0203943,0,2.09113,2.79749,0,0,0.0661323,0.163366
33,mauritania,0.123476,1.22818,0,0.833333,1.70662,1.35472,6.06689,1.07699,0,1.32174,0.384064,1.28596,0.333333,1.72436,3.97146,0.20339,0.220418,0.0994819,0.184453
34,afghanistan,0.175277,1.18188,0.332268,1.3913,2.23943,0.0929332,3.52715,0.444623,0.36258,1.30233,0.325962,1.2043,0,1.89599,3.35718,1.0735,1.13598,0.339452,0.560122
35,belgium,0.141346,1.40133,3.75,0.230922,2.70534,1.26143,6.86804,1.14309,0,0.0307167,1.41396,0.0411523,0,2.59665,4.80344,0.234375,0.23622,0.0330824,0.184524
36,central african republic,0.18282,0.0359685,0.123711,2.02439,1.20139,0.573705,2.47834,1.33259,0.12766,0.564706,0.162801,0.573705,0.488372,0.363115,1.45527,0.08,0.091954,0.0701262,0.10219
37,india,0.0606061,1.81761,0.506771,0.843436,2.06533,2.41141,1.52219,0.33,0.535135,0.358396,0.107888,1.14553,0.407407,1.72643,2.15594,0.0148148,0.0287582,0.158158,0.230568
38,burkina faso,0.0873617,1.1875,0.186047,1.15861,1.3172,1.05,7.36682,0.252336,0.30988,1.32582,0.394243,1.03562,1.2233,1.1927,2.26789,1.09091,0.220645,0.200549,0.479574
39,france,0.124078,1.20879,0,0.224915,1.73382,1.16485,5.28495,1.09009,0.288462,0.0305292,1.57718,0.0203943,0,1.74442,2.26682,0.16129,0,0.0529344,0.050399
40,pakistan,0.0509915,1.15094,0.0354384,1.02857,1.97245,1.1208,1.84558,1.25035,0.0524495,1.1984,0.284746,0.276817,0,1.92039,2.82473,1.50576,1.48699,0.151129,0.317308
41,chile,0.0512856,1.04681,0,0.159521,2.17917,1.14667,7.71429,1.03522,0,1.14497,0.228838,1.03026,0,2.1001,1.0408,0.12,0.116883,0.055132,0.0912382
42,indonesia,0.0533702,1.16914,0.442516,0.582524,2.80948,0.313922,1.58241,1.2333,0.5,1.18541,0.420526,1.08333,1.03448,2.31648,2.36182,2.70169,2.42326,0.133131,0.199537
43,madagascar,0.153444,1.04675,0.350562,1.31417,1.57081,1.22372,7.44942,1.10652,0.482226,1.19903,0.413805,1.19575,0.764706,1.20716,1.62354,0.166502,0.168495,0.106625,0.211726
44,latvia,0.109945,1.29926,0,1.3662,2.68195,1.0158,10.1887,1.05831,0,0.0841515,0.225861,0.0842105,0,1.97809,2.02102,0.247934,0.244565,0.134155,0.173745
45,estonia,0.0668774,0.4607,0,1.75286,2.11474,0.994742,6.90698,0.0734266,0,0.0317613,0.307704,0.0317919,0,1.75538,1.53682,0.150685,0.19469,0.0659329,0.0494104
46,malta,0.10509,0.253968,0,0.323964,2.38652,1.07143,3.27273,0.0794206,0,0.308571,0.201587,0.30916,0,2.06298,1.86218,0.133333,0.141176,0.069953,0.0693642
47,spain,0.120702,1.2474,0.6,1.22207,2.23196,0.21692,8.05167,1.02339,0.517241,0.0413508,0.275283,0.0310131,0,2.13563,1.83521,0,0,0.06718,0.122951
48,suriname,0.0999437,1.30529,0,0.350711,1.4826,0.0471143,0,0.121279,0,0.139697,0.197487,0.151163,1.80328,1.46552,2.34005,0,0.0292398,0.0716949,0.115321
49,south africa,0.267763,1.07553,0.264586,0.231925,1.58794,1.15268,7.77067,1.21759,0.450704,1.1134,0.164941,1.07347,1.33425,1.49934,1.7582,1.54846,1.51832,0.081383,0.0155199
50,lithuania,0.094841,1.99006,0,0.42113,2.00178,0.0527426,8.1746,1.15607,0,1.00527,0.340597,0.0636042,0,1.87136,1.54557,0.27027,0.233853,0.119393,0.174202
51,sao tome and principe,0.0594966,1.25861,0,1.66794,3.34717,1.11854,0,1.10626,0,0.0515021,1.33394,0.0517241,1.54128,2.23704,1.82522,0.279431,0.315375,0.108733,0.134831
52,bangladesh,0.145784,1.08354,0.688122,0,1.37848,1.21053,5.04168,0.422389,0.77367,1.0038,0.436918,0.126649,0,1.57803,3.4233,1.09877,1.45207,0.163602,0.236842
53,guinea,0.0415854,1.38728,0.139738,1.63107,2.21035,0.219409,3.2322,1.23543,0.159091,1.12871,0.530278,1.08159,1.0411,1.64662,3.47392,0.172043,0.17284,0.124272,0.121396
54,guatemala,0.13399,1.26502,0.330579,0.240629,1.42675,0.260181,0,0.130119,0.337838,1.09572,0.225428,0.260181,0,1.26726,3.06903,0.15625,0.15625,0.0823253,0.106486
55,mozambique,0.159155,1.8684,0.390385,1.68627,1.70803,0.748515,5.92212,1.28376,0.448299,0.163583,0.347357,1.06733,1.0283,1.58531,2.05126,0.131827,0.134875,0.30663,0.457193
56,albania,0.0691892,2.17476,1.45455,0.439288,2.24445,0.0306122,12.4028,1.06381,1.06667,0.0203822,0.174919,0.0203952,0,2.14208,4.28979,0.555985,0.529412,0.149322,0.296601
57,swaziland,0.251869,1.7254,0.375,1.60866,2.47064,1.10605,6.67939,1.14187,0.267857,0.145522,0.622549,0.157776,1.24904,1.86225,2.65047,0.768072,0.779412,0.0953307,0.223735
58,canada,0.0887718,1.06367,0,0.0858018,1.81561,1.8375,5.86389,1.11302,0,1.06931,1.51068,0.0872727,0,1.75699,2.39226,0,0.230769,0.0390589,0.00630915
59,croatia,0.0260459,1.67556,0,0.0881202,1.23588,0.0310881,5.51351,1.20369,0,0.0208333,0.103185,0.0208333,0,1.16572,1.90859,0.186047,0.126984,0.0334417,0.0620155
60,guyana,0.0198128,1.1242,1.75,0.163508,2.50458,1.01466,0,1.1655,0,1.01054,0.457323,1.01466,1.79487,2.3277,1.49744,0.0704403,0.0732984,0.0484038,0.138705
61,cambodia,0.0632213,1.27279,0.432,1.5643,1.3482,1.06931,3.7515,0.278976,0.554795,1.13808,0.47378,1.09168,1.6875,1.49285,2.27344,0.940594,0.0530973,0.134043,0.0757098
62,kenya,0.188306,0.529781,0.307329,1.21972,2.16873,1.19791,3.14463,1.26124,0.401743,1.22513,0.389593,1.20548,1.625,1.61043,3.12162,0.131919,0.145931,0.191735,0.286474
63,portugal,0.155155,1.55889,5,0.354589,2.02347,1.04678,6.25,1.28201,2.5,0.0518672,1.07637,0.0618982,0,1.93269,1.42318,0.138889,0.185185,0.074757,0.0880872
64,costa rica,0.0254691,1.44828,0,0.254799,2.45217,1.09601,5,1.09702,0,1.27069,0.302784,1.08953,0,2.31553,1.9382,0.353535,0.3125,0.0898693,0.180439
65,timor-leste,0.0268085,0.0806023,0,4.39744,1.42689,0.210526,6.00112,0.145176,0.388889,0.222015,0.691589,0.210526,0,1.52964,2.20074,0.975818,0.0526316,0.0895522,0.0649652
66,austria,0.121502,1.35258,0,0.15528,1.57509,0.809801,7.24919,1.09091,0,0.315666,2.13983,0.196911,0,1.53572,1.22098,0.0581395,0.0519031,0.0685728,0.0911854
67,myanmar,0.111743,2.12492,0.534562,2.00484,2.72464,1.38583,2.34049,1.17749,0.595265,1.25599,0.409148,1.13533,0.590164,1.78999,1.73293,0.0304956,0.0373367,0.204648,0.16568
68,ecuador,0.0428801,1.11974,0.401786,0.160217,3.02777,1.11443,11.6114,1.13885,0.451128,1.12245,0.982993,0.144552,1,2.97448,1.90478,0.287081,0.3125,0.0991095,0.123584
69,belarus,0.0831581,1.08505,1.66667,0.486763,3.24408,1.0423,5.65823,1.0177,1.07143,1.00822,0.319767,1.02471,0,2.24993,1.45667,0.358209,0.338983,0.163602,0.176951
70,algeria,0.0417739,1.21574,0.0986547,1.45325,1.84292,1.13793,5.08346,1.07626,0.0856031,0.0965854,0.802757,0.0963973,0,1.69678,1.61987,0.05,0.0509259,0.0961563,0.20511
71,germany,0.13549,1.21735,0.394737,0.169409,1.88615,1.02954,4.20455,1.08173,0.306122,0.0316233,2.52864,0.982874,0,1.85974,2.29679,0.0892857,0.0903614,0.0728264,0.0482897
72,sierra leone,0.179659,1.24683,0.228571,1.63383,1.95646,0.348872,3.15567,1.23605,0.33657,0.35312,1.5114,0.336336,1.16364,2.06439,3.224,0.170732,0.184615,0.177207,0.147518
73,georgia,0.0381229,1.14035,0.833333,1.05453,2.01911,0.630473,5.78994,1.05553,0.789474,1.05546,1.11722,1.08696,0,2.09746,5.28551,0.181598,0.103448,1.12958,0.166755
74,comoros,0.103323,1.05795,0.545455,1.76271,1.52143,0.810631,10.9222,1.20558,0,1.07605,0.662518,1.08096,2.47059,1.14827,1.48658,0.11124,0.141677,1.27002,0.185819
75,trinidad and tobago,0.123316,1.01949,0,0.290521,2.93023,1.53947,0,1.11216,6.5,1.09275,0.38764,1.303,3.07895,2.76621,1.58374,0.114899,0.154946,0.0752208,0.0645562
76,fiji,0.0291404,1.81291,0,1.57247,3.06371,0.0101146,5.71875,1.13962,0,0.0824742,0.338693,0.986842,0,1.60682,1.25439,0.0731707,0.0789474,0.0657018,0.148866
77,vanuatu,0.126145,1.10123,0,1.52479,1.80282,1.11511,8.38983,1.06979,0,0.0301811,0.488715,1.08967,0,1.47426,1.93151,0.127119,0.2,1.69254,0.113708
78,bhutan,0.116808,1.22229,1.36364,3.40909,2.08754,0.170576,8.90809,1.24416,0,1.00225,0.781893,0.138988,1.44231,1.9172,1.6401,0.201845,0.204948,3.82378,0.526142
79,australia,0.0744746,1.10526,0,0.121131,1.92587,0.0428135,3.21404,1.08869,0.736842,0.0108865,0.149333,0.0217391,0,1.90755,6.52173,0.148936,0.16092,0.0402925,0.0850608
80,romania,0.09326,0.279188,0.697674,1.32573,2.70164,0.0513699,5.10963,0.153744,0.9,0.115627,0.284199,0.104822,0,2.42623,2.6376,0.435685,0.421348,0.124956,0.309947
81,thailand,0.0479715,1.10422,0.806452,0.110906,1.87092,0.0412939,2.2477,1.45239,0.760369,0.0203528,0.226224,0.0305707,1.72131,1.83937,2.04093,0.186047,0.21673,0.140214,0.224359
82,zambia,0.239301,1.37568,0.196721,1.22101,1.60704,1.13307,5.05733,1.21893,0.298507,1.44295,0.644531,1.13307,1.33263,1.70944,1.98433,0.119403,0.121951,0.197129,0.15411
83,italy,0.116855,1.31319,0.483871,0.342339,1.73529,0.0313589,5.27592,1.01701,0.428571,0.0207612,0.172034,0.105411,0,1.69309,2.02033,0.197368,0.192308,0.0630448,0.11316
84,cabo verde,0.0812414,1.22949,0,1.54232,1.94504,1.18296,0,1.08093,0,1.01124,0.347628,1.01474,1.35821,1.64451,1.85063,0.304094,0.305284,0.121587,0.20389
85,china,0.0553008,1.42466,1.04911,0.705404,3.96329,1.17424,1.85775,1.39557,1.13531,0.139286,0.300935,0.150646,0,3.08152,3.96071,0.467422,0.512195,0.213632,0.318584
86,iraq,0.174738,1.70931,0.0634006,2.38462,2.42462,0.320388,6.80177,0.119624,0.0521327,1.33049,0.657254,0.320106,0,1.89675,2.29105,0.0186757,0.0195382,0.0874131,0.0683837
87,jamaica,0.0362335,1.11439,0,0.138728,2.88968,1.09091,8,1.05688,0,1.02857,0.331643,1.03152,1.80952,2.06742,2.16671,0.0538117,0.0582524,0.0531902,0.136364
88,haiti,0.0063593,0.0321285,0,1.99297,0.0224983,0.344828,0,0.0227979,0,0.196721,0.0689655,0.344828,0,0.0224983,0.0936609,0,0,0.00824742,0
89,belize,0.0260291,1.1738,0,0.391833,1.58582,0.232068,0,1.11828,0,0.0732218,0.381003,0.0944717,3.13433,1.13769,2.06254,0.11236,0.0858779,0.0548235,0.0965147
90,jordan,0.0315443,1.05708,0,0.405928,2.35927,0.0516173,4.24528,1.12538,0,0.0412371,0.304054,0.0825877,0,1.97228,1.62046,0.0515464,0.0518135,0.0576765,0.0905888
91,maldives,0.114149,1.45276,0,1.39981,3.06382,0.0306748,8.28385,1.27444,0,0.0306748,0.965196,0.0306748,0,2.18719,1.28674,0.0843091,0.0767442,0.182831,0.117122
92,poland,0.0476653,1.31858,0.441176,0.389052,3.89269,0.0410397,2.62846,1.0282,0.731707,0.051511,0.253945,0.0101215,0,2.22341,2.59593,0.269461,0.293296,0.0900567,0.118629
93,philippines,0.023699,0.0412088,0.242718,0.208395,2.22599,1.24494,7.76267,1.20916,0.276151,1.04949,0.491635,0.285714,0,2.18829,2.48288,0,0.0103164,0.0894326,0.0260116
94,montenegro,0.0279751,1.57604,0,1.63161,0.363202,1.87593,4.5,1.17234,0,1.02653,0.287871,1.02381,0,0.452852,2.06768,0.202247,0.147541,0.066383,0.130534
95,turkmenistan,0.0417957,1.05798,0.152941,0.225629,3.19566,0.0308789,6.39167,1.16965,0,0.346527,0.908723,0.166267,0,3.19055,2.2159,0.0909091,0.0599078,3.29096,0.0572267
96,eritrea,0.139139,1.04959,0.153846,0.96732,2.09801,1.04442,3.70072,0.232877,0.217391,1.03851,0.359334,1.15285,0.882353,1.95513,1.99411,0.118407,0.12945,1.67285,0.197628
97,brazil,0.0545901,1.0974,0.957143,0.101201,2.62833,0.0831601,10.0152,1.07619,0.98402,0.0305085,0.244409,0.0611829,0,2.14577,2.11477,0.227766,0.230263,0.0989726,0.134816
98,russian federation,0.12455,1.36053,0.482759,0.184892,4.28129,0.597826,3.24313,0.100681,0.522388,0.0102414,0.43148,0.0205731,1.07692,2.32119,2.48108,0.20649,0.269231,0.108791,0.174274
99,ethiopia,0.151425,1.09649,0.286381,1.52107,1.47306,0.48,2.57227,0.170481,0.35,1.53672,0.484166,1.24946,1.35385,1.51724,1.7113,1.52827,3.4955,0.180861,0.161742
100,liberia,0.146347,0.255658,0.21875,1.8036,1.29941,1.47801,6.00858,0.131774,0.244186,1.2009,1.51079,1.61702,0.954545,1.2921,1.45621,0.138889,0.156187,0.0782123,0.0412371
101,seychelles,0.0165929,1.06387,0,1.79639,3.02987,0.0303849,13.6364,1.19036,0,0.030426,0.568122,0.030426,0,2.27087,1.52331,0.101351,0.110759,1.11857,0.109148
102,mexico,0.0237927,1.06042,0.596026,0.11537,2.23022,0.178446,5.45455,1.12026,0.634697,0.167364,0.266711,0.167481,0,1.86397,4.28253,0.229008,0.238095,0.0825385,0.138662
103,argentina,0.0279113,1.25517,0.4,0.109937,1.72602,1.05843,8.5,1.02414,0.356164,0.0846906,0.53772,0.0747126,0,1.82375,2.03869,0.188406,0.107438,0.0691155,0.0721554
104,cameroon,0.07109,1.27987,0.206767,1.55082,1.86303,1.06439,1.59225,0.197828,0.266344,1.06809,0.369819,1.17391,0.645724,1.59139,2.52173,0.192308,0.207006,0.106762,0.256959
105,burundi,0.116015,1.34004,0.0869565,1.69619,2.08179,0.17154,4.35556,0.278641,0.173684,0.22,1.30337,0.17154,1.61649,1.96174,2.11253,0.127907,0.140534,0.365691,0.652747
106,nepal,0.0789376,1.39716,0.75,1.25301,2.26372,1.42292,3.43002,0.357447,0.809639,1.16173,0.208478,1.15862,0.571429,1.59022,2.00758,0.123894,0.131679,0.187282,0.299532
107,solomon islands,0.0443699,1.69331,0,1.49875,2.68957,1.16379,0,1.09367,0,1.03448,0.536113,1.21841,0,2.51514,1.67485,0.239362,0.157895,0.146444,0.349922
108,angola,0.153922,0.0744314,0.261011,0.259843,1.33113,0.225352,2.91266,1.10027,0.311579,0.253968,0.29285,1.10938,0.244898,1.40302,2.37033,0.121715,0.145658,0.148111,0.390501
109,tunisia,0.0296123,5.06689,0.306122,0.221261,1.45742,0.0724138,6.69903,1.13307,0.535714,0.0409556,0.325476,0.0409556,0,1.28939,3.62172,0.046875,0.0315789,0.110049,0.135521
110,israel,0.0627924,1.1745,0,0.220235,2.77505,0.0307587,6.50257,1.07682,0,0.0530786,0.101622,0.981941,0,2.10571,2.79476,0.0877193,0,0.0573702,0.0573492
111,malawi,0.270585,1.42184,0.526652,1.42932,2.64959,0.390223,12.8073,0.259528,0.616531,0.220713,1.69707,0.390223,1.20473,2.01367,2.58934,0.170306,0.187778,0.254183,0.108251
112,ukraine,0.157488,1.23507,0.38961,0.698842,2.4944,1.65493,7.43302,1.06574,0.5,0.646965,0.327562,1.28532,1.42857,2.47445,4.7373,0.269923,0.259901,0.107773,0.137363
113,kazakhstan,0.0903433,1.16501,0.545455,0.278559,3.68059,0.0514051,12.4463,1.04646,0.604839,0.0512996,0.375684,0.176471,0,2.8585,2.23549,0.163934,0.078534,0.152318,0.207736
114,gabon,0.0650794,1.16289,0,1.16922,2.68632,1.19808,4.82213,1.04678,0,1.18314,0.456418,1.17371,1.11111,1.69868,1.57084,0.166163,0.169492,0.0712985,0.0160514
115,mali,0.104693,1.13887,0.126697,1.42292,1.52428,1.09765,5.68543,1.23894,0.222812,1.13684,0.109589,0.210526,0.409756,1.27706,3.00695,1.15789,1.17303,0.298071,0.44665
116,colombia,0.0437238,1.23577,0.495283,0.0927742,2.67244,1.08696,13.8079,1.05539,0.54,1.01432,0.288644,1.08418,0,2.237,1.54379,0.216138,0.191693,0.103083,0.205931
117,togo,0.0602558,1.1403,0.0721649,1.90667,1.56652,0.84,1.39208,1.26249,0.0952381,1.06312,0.278689,0.108247,1.35025,1.10786,1.59427,0.154,0.171429,0.0744215,0.167929
118,kiribati,0.0307346,1.76188,0,1.70197,2.2724,1.21766,0,1.0089,0,1.09114,2.18401,1.23104,0,1.4242,2.52212,0.625,0.714286,1.71093,0.205479
119,equatorial guinea,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [34]:
#interestingly equatorial guinea has only zeros in the dataframe above: the explanation is very simple: we removed all rows but one when we got rid of null values. si min - max = 0 everywhere

In [35]:
#let's analyse this dataframe with pandas profiling
#df0_test_results.profile_report()

In [36]:
#looking around at the report generated above, we have the confirmation that the Kaggle data is absolute rubbish: a very significant number of values tend to be multiplied by 10 between one year and another, or to be completely out of range.
#it is now very clear that this data has been reverse engineered to get some sort of good correlation
#takeaway: even if a data set has a sliver medal on Kaggle and everyone cites it as a reference, this doesn't make the dataset good.

In [37]:
#we are going to have to build this from scratch, let's start by importing our new life expectancy dataframe

# Importing multiple datasets

In [38]:
ls data/gap_minder

countries+countrycode/
gap_minder_all_forms_of_tb_new_cases_per_100000_estimated.csv
gap_minder_at_least_basic_sanitation_overall_access_percent.csv
gap_minder_at_least_basic_water_source_overall_access_percent.csv
gap_minder_child_mortality_0_5_year_olds_dying_per_1000_born.csv
gap_minder_food_supply_kilocalories_per_person_and_day.csv
gap_minder_gdppercapita_us_inflation_adjusted.csv
gap_minder_gini.csv
gap_minder_government_share_of_total_health_spending_percent.csv
gap_minder_life_expectancy_at_birth_data_from_ihme.csv
gap_minder_life_expectancy_years.csv
gap_minder_malaria_cases_per_100000_reported.csv
gap_minder_medical_doctors_per_1000_people.csv
gap_minder_newly_hiv_infected_percent_age_15_49.csv
gap_minder_population_total.csv

In [39]:
df00 = pd.read_csv("data/gap_minder/gap_minder_life_expectancy_years.csv")

In [40]:
df00

,country,1800,1801,1802,1803,1804,1805,1806,1807,1808,1809,1810,1811,1812,1813,1814,1815,1816,1817,1818,1819,1820,1821,1822,1823,1824,1825,1826,1827,1828,1829,1830,1831,1832,1833,1834,1835,1836,1837,1838,1839,1840,1841,1842,1843,1844,1845,1846,1847,1848,1849,1850,1851,1852,1853,1854,1855,1856,1857,1858,1859,1860,1861,1862,1863,1864,1865,1866,1867,1868,1869,1870,1871,1872,1873,1874,1875,1876,1877,1878,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1899,1900,1901,1902,1903,1904,1905,1906,1907,1908,1909,1910,1911,1912,1913,1914,1915,1916,1917,1918,1919,1920,1921,1922,1923,1924,1925,1926,1927,1928,1929,1930,1931,1932,1933,1934,1935,1936,1937,1938,1939,1940,1941,1942,1943,1944,1945,1946,1947,1948,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035,2036,2037,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047,2048,2049,2050,2051,2052,2053,2054,2055,2056,2057,2058,2059,2060,2061,2062,2063,2064,2065,2066,2067,2068,2069,2070,2071,2072,2073,2074,2075,2076,2077,2078,2079,2080,2081,2082,2083,2084,2085,2086,2087,2088,2089,2090,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
0,Afghanistan,28.2,28.2,28.2,28.2,28.2,28.2,28.1,28.1,28.1,28.1,28.1,28.1,28.1,28.1,28.1,28.1,28.1,28.0,28.0,28.0,28.0,28.0,28.0,28.0,28.0,27.9,27.9,27.9,27.9,27.9,27.9,27.9,27.9,27.9,27.9,27.9,27.8,27.8,27.8,27.8,27.8,27.8,27.8,27.8,27.8,27.8,27.7,27.7,27.7,27.7,27.7,27.7,27.7,27.7,27.7,27.6,27.6,27.6,27.6,27.6,27.6,27.6,27.6,27.6,27.6,27.5,27.5,27.5,27.5,27.5,27.5,27.6,27.6,27.7,27.8,27.8,27.9,27.9,28.0,28.1,28.1,28.2,28.3,28.3,28.4,28.5,28.5,28.6,28.6,28.7,28.8,28.8,28.9,29.0,29.0,29.1,29.1,29.2,29.3,29.3,29.4,29.5,29.5,29.6,29.7,29.7,29.8,29.9,29.9,30.0,30.0,30.1,30.2,30.2,30.3,30.3,30.4,30.5,7.97,30.6,30.6,30.7,30.8,30.8,30.9,31.0,31.0,31.1,31.1,31.2,31.3,31.3,31.4,31.4,31.5,31.6,31.6,31.7,31.8,31.8,31.9,31.9,32.0,32.1,32.1,32.2,32.2,32.3,32.4,32.4,32.5,32.9,33.6,34.3,35.0,35.7,36.4,37.1,37.9,38.6,39.3,40.0,40.8,41.5,42.3,43.0,43.7,44.5,45.2,45.9,46.6,46.8,46.8,46.9,47.0,47.1,47.3,47.5,45.9,44.4,44.1,44.9,44.6,42.8,40.5,42.4,43.4,45.5,47.9,51.7,52.6,52.4,52.9,53.1,52.7,53.3,53.8,53.7,52.8,54.4,54.6,54.8,55.6,56.4,56.9,57.4,57.6,58.0,58.8,59.3,59.9,60.4,60.8,61.3,61.2,61.2,61.2,63.4,63.7,64.1,64.4,64.7,65.1,65.4,65.7,65.9,66.2,66.5,66.7,67.0,67.2,67.4,67.7,67.9,68.1,68.3,68.5,68.7,68.9,69.0,69.2,69.4,69.6,69.7,69.9,70.1,70.2,70.4,70.5,70.7,70.8,71.0,71.1,71.3,71.4,71.6,71.7,71.8,72.0,72.1,72.3,72.4,72.5,72.7,72.8,72.9,73.1,73.2,73.3,73.5,73.6,73.7,73.9,74.0,74.2,74.3,74.4,74.6,74.7,74.8,75.0,75.1,75.2,75.4,75.5,75.6,75.8,75.9,76.0,76.2,76.3,76.5,76.6,76.7,76.9,77.0,77.1,77.3,77.4,77.5,77.7
1,Albania,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,19.40,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,35.4,36.3,37.2,38.1,39.0,39.9,40.7,41.6,42.5,43.4,43.0,42.0,41.5,40.0,37.0,34.0,47.0,50.0,51.5,52.4,53.3,54.1,54.4,54.8,55.4,56.1,57.0,57.9,58.9,60.0,61.1,62.2,63.3,64.2,64.9,65.4,65.8,66.1,66.3,66.4,66.6,66.9,67.5,68.1,68.7,69.3,69.8,70.3,70.8,71.2,71.5,71.7,71.8,72.0,72.1,72.3,72.4,72.6,72.6,72.8,73.1,73.3,73.0,73.4,73.9,74.5,74.6,74.4,72.5,74.5,74.6,74.9,75.2,75.3,75.4,75.6,76.0,76.4,76.9,77.0,77.5,77.6,77.7,77.8,77.9,77.9,78.0,78.1,78.2,78.3,78.5,78.6,78.7,78.8,78.9,79.1,79.2,79.3,79.5,79.7,79.8,80.0,80.2,80.3,80.5,80.6,80.8,80.9,81.0,81.2,81.3,81.4,81.6,81.7,81.8,82.0,82.1,82.3,82.4,82.5,82.7,82.8,83.0,83.1,83.2,83.4,83.5,83.6,83.7,83.9,84.0,84.1,84.2,84.3,84.5,84.6,84.7,84.8,84.9,85.0,85.1,85.2,85.3,85.4,85.5,85.7,85.8,85.8,86.0,86.0,86.2,86.3,86.4,86.5,86.6,86.7,86.8,86.9,87.0,87.1,87.2,87.3,87.4,87.5,87.6,87.7,87.8,87.9,88.0,88.1,88.2,88.3
2,Algeria,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,20.0,15.0,22.0,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,28.8,21.0,11.0,15.0,22.0,28.9,28.9,29.0,29.0,29.0,29.1,29.1,29.2,29.2,29.3,29.3,29.4,29.4,29.4,29.5,29.5,29.6,29.6,29.7,29.7,29.8,29.8,29.8,29.9,29.9,30.0,30.0,30.1,30.1,30.2,30.3,30.4,31.4,25.4,28.1,29.6,29.5,29.5,31.0,32.7,32.4,33.8,31.6,31.1,30.6,30.3,30.3,23.70,30.4,29.6,29.6,29.4,32.0,33.5,34.3,33.6,28.8,32.4,32.7,34.0,31.9,33.3,34.6,34.0,35.9,37.1,35.2,34.6,36.9,37.3,35.6,34.9,30.2,35.7,33.5,35.7,39.1,42.3,44.8,47.3,47.5,48.0,48.6,49.1,49.6,50.2,50.8,51.3,51.9,52.5,53.1,53.7,54.3,54.9,55.4,56.0,56.5,57.0,57.6,58.1,58.4,58.8,59.2,59.7,60.1,60.6,61.2,61.8,62.5,62.8,64.0,65.1,66.4,67.6,68.7,69.5,70.2,70.8,71.3,71.7,72.2,72.5,72.7,72.8,72.9,73.3,73.2,73.5,73.9,74.0,74.2,74.5,74.6,75.0,75.3,75.5,75.7,75.9,76.1,76.3,76.5,76.8,76.9,77.0,77.1,77.4,77.7,77.9,78.1,78.3,78.5,78.7,78.8,79.0,79.2,79.4,79.6,79.7,79.9,80.1,80.3,80.4,80.6,80.8,80.9,81.1,81.2,81.4,81.6,81.7,81.9,82.0,82.2,82.3,82.5,82.7,82.8,83.0,83.1,83.3,83.4,83.6,83.7,83.8,84.0,84.1,84.3,84.4,84.6,84.7,84.8,85.0,85.1,85.2,85.3,85.5,85.6,85.7,85.8,86.0,86.1,86.2,86.3,86.4,86.5,86.7,86.8,86.9,87.0,87.1,87.2,87.3,87.4,87.5,87.6,87.7,87.8,87.9,88.0,88.2,88.3,88.4,88.5,88.6,88.7,88.8,88.9,89.0,89.1,89.2
3,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.5,75.8,76.1,76.4,76.7,77.0,77.2,77.5,77.8,78.1,78.2,78.3,78.3,78.3,78.5,78.6,78.7,78.8,78.8,78.9,79.0,79.1,79.1,79.3,79.5,79.7,80.0,80.3,80.6,80.9,81.2,81.4,81.6,81.7,81.7,81.8,82.0,82.1,82.2,82.2,82.3,82.4,82.4,82.5,82.5,82.6,82.7,82.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.1,27.1,27.2,27.3,27.3,27.4,27.5,27.5,27.6,27.7,27.7,27.8,27.9,27.9,28.0,28.1,28.1,28.2,28.3,28.4,28.4,28.5,28.6,28.6,28.7,28.8,28.8,28.9,29.0,29.0,29.1,29.2,29.3,29.3,29.4,29.4,29.5,29.6,29.7,29.7,29.8,29.9,29.9,30.0,30.1,30.1,30.2,11.70,30.4,30.4,30.5,30.6,30.6,30.7,30.8,30.8,30.9,31.0,31.0,31.1,31.2,31.2,31.3,31.4,31.4,31.5,31.6,31.6,31.7,31.8,32.1,32.5,32.8,33.1,33.5,33.8,34.1,34.5,34.8,35.2,35.5,36.0,36.6,37.1,37.7,38.3,38.8,39.4,40.0,40.6,41.1,41.7,42.3,42.9,43.5,44.1,44.7,45.3,45.9,46.5,46.7,46.9,47.1,47.3,47.2,47.2,47.3,47.4,47.5,47.6,47.7,47.7,47.7,47.8,47.9,47.9,47.7,47.5,47.8,47.9,48.5,48.6,47.3,48.7,49.5,50.1,50.2,49.3,50.7,51.7,52.4,53.5,54.2,54.8,55.7,56.4,57.5,58.4,59.1,59.9,60.6,61.3,61.9,62.8,63.3,63.8,64.2,64.6,65.0,65.4,65.7,66.0,66.4,66.7,67.0,67.3,67.6,67.9,68.2,68.5,68.8,69.1,69.3,69.6,69.9,70.1,70.4,70.6,70.8,71.1,71.3,71.5,71.7,71.9,72.1,72.3,72.5,72.7,72.8,73.0,73.2,73.3,73.5,73.7,73.8,74.0,74.2,74.3,74.5,74.6,74.8,74.9,75.0,75.2,75.3,75.5,75.6,75.7,75.9,76.0,76.2,76.3,76.4,76.5,76.7,76.8,77.0,77.1,77.2,77.3,77.5,77.6,77.7,77.8,78.0,78.1,78.2,78.4,78.5,78.6,78.7,78.9,79.0,79.1,79.3,79.4,79.5,79.7,79.8,79.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,Venezuela,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.2,32.3,32.3,32.3,32.3,32.3,32.3,32.3,32.3,32.3,32.3,32.3,32.3,32.3,32.3,32.3,32.4,32.4,32.4,32.4,32.4,32.4,32.4,32.4,32.4,32.4,32.4,32.4,32.4,32.4,32.5,32.5,32.5,32.5,32.5,32.5,32.5,32.5,32.5,32.5,32.5,32.5,29.40,32.5,32.5,32.5,32.6,32.6,32.6,32.6,32.6,32.8,32.9,33.1,33.3,33.5,33.7,33.8,34.0,34.2,34.4,35.6,36.8,38.0,39.3,40.5,42.1,43.7,45.3,46.9,48.5,50.1,51.8,53.4,55.0,55.3,55.9,56.5,57.0,57.6,58.2,58.8,59.5,60.0,60.7,61.3,61.9,62.5,63.1,63.6,64.2,64.8,65.3,65.8,66.3,66.3,66.3,66.4,66.9,67.3,67.8,68.5,68.8,69.2,69.4,69.8,70.0,70.5,70.9,71.2,71.7,71.6,71.8,71.9,72.1,72.6,72.6,72.5,72.1,72.4,73.0,73.7,73.7,70.1,74.0,74.0,74.0,73.5,74.7,75.2,75.2,75.0,74.7,74.8,75.3,75.3,75.2,75.2,75.0,75.0,75.3,75.3,75.2,75.1,75.1,75.2,75.3,75.5,75.8,76.0,76.3,76.6,76.8,77.0,77.2,77.3,77.5,77.6,77.8,77.9,78.1,78.2,78.4,78.5,78.7,78.8,79.0,79.1,79.3,79.4,79.6,79.7,79.9,80.0,80.2,80.3,80.5,80.6,80.8,80.9,81.1,81.2,81.4,81.5,81.7,81.8,82.0,82.1,82.3,82.5,82.6,82.8,82.9,83.0,83.2,83.3,83.5,83.7,83.8,84.0,84.1,84.2,84.4,84.5,84.7,84.8,85.0,85.1,85.3,85.4,85.5,85.7,85.8,86.0,86.1,86.2,86.3,86.5,86.6,86.7,86.9,87.0,87.1,87.2,87.3
183,Vietnam,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,31.9,31.9,31.9,31.9,31.8,31.8,31.8,31.8,31.7,31.7,31.7,31.6,31.6,31.6,31.6,31.5,31.5,31.5,31.4,31.4,31.4,31.4,31.3,31.3,31.3,31.2,31.2,31.2,31.2,31.1,31.1,31.1,31.1,31.0,31.0,31.0,30.9,30.9,30.9,30.9,30.8,30.8,30.8,30.7,30.7,30.7,19.60,30.6,30.6,30.6,30.5,30.5,30.5,30.5,30.4,30.4,30.4,30.4,30.3,30.4,30.6,30.7,30.8,31.0,31.1,32.3,33.6,34.8,33.8,32.9,32.3,30.9,25.3,15.9,33.6,39.2,43.8,46.5,48.2,48.6,49.3,50.0,50.7,51.4,52.0,52.6,53.2,53.8,54.4,55.0,55.5,56.1,56.5,56.8,56.9,56.5,56.0,55.2,54.4,55.1,51.1,55.2,54.1,61.8,63.7,64.0,64.5,63.8,65.1,65.6,66.0,66.3,66.8,67.2,67.6,67.9,68.3,68.6,68.9,69.1,69.4,69.6,69.9,70.2,70.5,70.7,71.1,71.3,71.5,71.7,71.9,72.1,72.3,72.5,72.7,72.8,73.0,73.2,73.5,73.6,73.8,74.0,74.1,74.3,74.4,74.5,74.6,74.7,74.8,74.9,75.0,75.1,75.2,75.4,75.5,75.7,75.8,76.0,76.1,76.3,76.5,76.6,76.8,76.9,77.1,77.2,77.3,77.5,77.6,77.8,77.9,78.0,78.2,78.3,78.5,78.6,78.8,78.9,79.0,79.2,79.3,79.5,79.6,79.8,79.9,80.1,80.2,80.3,80.5,80.6,80.8,80.9,81.1,81.2,81.3,81.5,81.6,81.7,81.8,82.0,82.1,82.2,82.3,82.5,82.6,82.7,82.8,83.0,83.1,83.2,83.3,83.4,83.5,83.6,83.8,83.9,84.0,84.1,84.2,84.3,84.4,84.5,84.6,84.7,84.8,84.9,85.0,85.2,85.3
184,Yemen,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.4,23.5,23.5,23.5,23.5,23.5,23.5,23.5,23.5,23.5,23.5,23.5,23.5,23.5,23.5,23.5,23.5,23.5,23.5,23.5,23.6,23.6,23.6,23.6,23.6,23.6,23.6,23.6,23.6,23.6,23.6,23.6,23.6,19.60,23.6,23.6,23.6,23.6,23.6,23.6,23.6,23.6,23.6,23.6,23.6,23.7,23.7,23.7,23.7,23.7,23.7,23.7,23.7,23.7,23.7,23.7,23.7,23.7,23.7,23.7,23.7,23.7,23.7,23.7,23.8,23.8,24.2,25.2,26.2,27.1,28.1,29.1,30.1,31.0,32.0,33.0,33.9,34.9,35.8,36.7,37.6,38.5,39.4,40.3,41.1,42.0,44.5,45.4,46.6,47.6,48.6,49.6,50.7,51.5,52.4,53.1,53.9,54.1,55.4,56.0,56.5,54.6,57.5,57.9,58.3,58.7,59.2,59.6,60.0,60.2,60.9,61.2,61.7,62.2,62.8,63.3,63.9,64.4,64.8,65.3,65.9,66.4,66.8,67.2,67.5,68.0,68.1,68.3,68.9,69.0,68.6,68.1,68.1,68.1,68.1,68.2,68.3,68.3,68.5,68.6,68.8,68.9,69.1,69.3,69.6,69.8,70.0,70.2,70.4,70.6,70.8,70.9,71.0,71.1,71.3,71.4,71.5,71.6,71.8,71.9,72.0,72.1,72.2,72.3,72.5,72.6,72.7,72.8,72.9,73.0,73.2,73.3,73.4,73.5,73.6,73.7,73.8,73.9,74.0,74.2,74.3,74.4,74.5,74.6,74.7,74.8,75.0,75.1,75.2,75.3,75.4,75.5,75.6,75.8,75.9,76.0,76.1,76.2,76.3,76.5,76.6,76.7,76.8,76.9,77.1,77.2,77.3,77.4,77.5,77.7,77.8,77.9,78.0,78.2,78.3,78.4
185,Zambia,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.6,32.7,32.7,32.7,32.8,32.8,32.8,32.9,32.9,32.9,33.0,33.0,33.0,33.1,33.1,33.1,33.2,33.2,33.2,33.3,33.3,33.3,33.4,33.4,33.4,33.5,33.5,33.5,33.5,33.6,33.6,33.6,33.7,33.7,33.8,33.8,33.8,33.9,33.9,33.9,33.9,34.0,34.0,34.0,34.1,34.1,34.1,13.20,34.2,34.2,34.3,34.3,34.3,34.4,34.4,34.4,34.5,34.5,34.5,34.6,34.6,34.6,34.7,34.7,34.7,34.8,34.8,34.8,34.9,34.9,34.9,35.0,35.0,35.0,35.1,37.0,38.9,40.8,42.6,44.5,44.8,45.3,45.8,46.3,46.8,47.3,47.8,48.3,48.7,49.2,49.7,50.1,50.5,51.0,51.4,51.9,52.4,52.9,53.4,54.0,54.4,54.9,55.3,55.6,55.9,56.2,56.3,56.3,56.4,56.0,56.0,55.7,55.5,55.1,54.6,54.0,53.4,53.0,51.9,50.7,49.5,48.4,47.6,46.8,46.1,45.7,45.5,45.5,45.6,46.0,46.1,47.0,47.6,48.4,49.3,50.2,51.5,53.0,54.5,56.0,57.5,58.8,60.0,61.1,62.0,62.8,63.2,63.7,64.0,64.3,64.6,64.8,65.1,65.3,65.5,65.8,66.0,66.3,66.5,66.8,67.0,67.2,67.5,67.7,67.9,68.1,68.3,68.5,68.7,68.9,69.1,69.3,69.5,69.7,69.8,70.0,70.2,70.4,70.5,70.7,70.9,71.0,71.2,71.3,71.5,71.7,71.8,72.0,72.1,72.3,72.4,72.6,72.7,72.9,73.0,73.2,73.3,73.5,73.6,73.8,73.9,74.1,74.2,74.4,74.5,74.7,74.8,74.9,75.1,75.2,75.4,75.5,75.7,75.8,76.0,76.1,76.3,76.4,76.5,76.7,76.8,77.0,77.1,77.3,77.4,77.6,77.7,77.8,78.0,78.1
186,Zimbabwe,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.7,33.8,33.8,33.8,33.8,33.8,33.8,33.8,33.8,33.9,33.9,33.9,33.9,33.9,33.9,33.9,33.9,33.9,34.0,34.0,34.0,34.0,34.0,34.0,34.0,34.0,34.0,34.1,34.1,34.1,34.1,34.1,34.1,34.1,34.1,34.2,34.2,34.2,34.2,34.2,34.2,34.2,34.2,34.3,34.3,17.30,34.3,34.3,34.3,34.3,34.3,34.4,34.4,34.4,34.4,34.4,34.4,34.4,34.4,34.5,34.5,34.5,34.5,34.5,34.5,34.5,34.5,34.5,36.0,37.4,38.9,40.3,41.8,43.2,44.7,46.1,47.6,49.1,49.3,49.8,50.2,50.6,51.1,51.5,52.0,52.4,52.8,53.2,53.6,54.0,54.4,54.8,55.1,55.5,55.8,56.2,56.5,56.9,57.2,57.6,57.7,58.1,58.3,58.0,57.6,56.0,56.5,59.7,60.5,61.0,61.4,61.9,62.3,62.7,62.8,62.4,61.9,60.9,59.5,57.6,55.6,53.8,52.0,50.8,49.6,48.5,47.5,46.6,46.2,45.6,45.4,45.1,45.1,45.4,45.9,46.3,47.2,49.7,52.4,54.9,56.8,58.5,59.6,60.5,61.4,61.7,62.0,62.3,62.5,62.7,62.9,63.1,63.4,63.6,63.9,64.1,64.4,64.6,64.8,65.1,65.3,65.5,65.8,66.0,66.2,66.4,66.6,66.8,67.0,67.2,67.4,67.6,67.8,68.0,68.2,68.3,68.5,68.7,68.9,69.0,69.2,69.4,69.5,69.7,69.8,70.0,70.2,70.3,70.5,70.6,70.8,70.9,71.0,71.2,71.3,71.5,71.6,71.7,71.9,72.0,72.1,72.3,72.4,72.5,72.7,72.8,72.9,73.0,73.2,73.3,73.4,73.6,73.7,73.8,73.9,74.1,74.2,74.3,74.5,74.6,74.7,74.8,75.0,75.1,75.3,75.4,75.5,75.7

In [41]:
#let's only keep years 1990 to 2017
df00 = df00.drop(df00.columns.to_series()["1800":"1989"], axis=1)
df00 = df00.drop(df00.columns.to_series()["2018":], axis=1)

In [42]:
df00.head()

,country,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Afghanistan,52.6,52.4,52.9,53.1,52.7,53.3,53.8,53.7,52.8,54.4,54.6,54.8,55.6,56.4,56.9,57.4,57.6,58.0,58.8,59.3,59.9,60.4,60.8,61.3,61.2,61.2,61.2,63.4
1,Albania,73.3,73.0,73.4,73.9,74.5,74.6,74.4,72.5,74.5,74.6,74.9,75.2,75.3,75.4,75.6,76.0,76.4,76.9,77.0,77.5,77.6,77.7,77.8,77.9,77.9,78.0,78.1,78.2
2,Algeria,71.7,72.2,72.5,72.7,72.8,72.9,73.3,73.2,73.5,73.9,74.0,74.2,74.5,74.6,75.0,75.3,75.5,75.7,75.9,76.1,76.3,76.5,76.8,76.9,77.0,77.1,77.4,77.7
3,Andorra,79.0,79.1,79.1,79.3,79.5,79.7,80.0,80.3,80.6,80.9,81.2,81.4,81.6,81.7,81.7,81.8,82.0,82.1,82.2,82.2,82.3,82.4,82.4,82.5,82.5,82.6,82.7,82.7
4,Angola,47.9,48.5,48.6,47.3,48.7,49.5,50.1,50.2,49.3,50.7,51.7,52.4,53.5,54.2,54.8,55.7,56.4,57.5,58.4,59.1,59.9,60.6,61.3,61.9,62.8,63.3,63.8,64.2

In [43]:
df00 = df00.applymap(lambda s:s.lower() if type(s) == str else s) #lowercasing everything

In [44]:
df00.head()

,country,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,afghanistan,52.6,52.4,52.9,53.1,52.7,53.3,53.8,53.7,52.8,54.4,54.6,54.8,55.6,56.4,56.9,57.4,57.6,58.0,58.8,59.3,59.9,60.4,60.8,61.3,61.2,61.2,61.2,63.4
1,albania,73.3,73.0,73.4,73.9,74.5,74.6,74.4,72.5,74.5,74.6,74.9,75.2,75.3,75.4,75.6,76.0,76.4,76.9,77.0,77.5,77.6,77.7,77.8,77.9,77.9,78.0,78.1,78.2
2,algeria,71.7,72.2,72.5,72.7,72.8,72.9,73.3,73.2,73.5,73.9,74.0,74.2,74.5,74.6,75.0,75.3,75.5,75.7,75.9,76.1,76.3,76.5,76.8,76.9,77.0,77.1,77.4,77.7
3,andorra,79.0,79.1,79.1,79.3,79.5,79.7,80.0,80.3,80.6,80.9,81.2,81.4,81.6,81.7,81.7,81.8,82.0,82.1,82.2,82.2,82.3,82.4,82.4,82.5,82.5,82.6,82.7,82.7
4,angola,47.9,48.5,48.6,47.3,48.7,49.5,50.1,50.2,49.3,50.7,51.7,52.4,53.5,54.2,54.8,55.7,56.4,57.5,58.4,59.1,59.9,60.6,61.3,61.9,62.8,63.3,63.8,64.2

In [45]:
#now let's pivot this dataframe and create a "year" column
df00 = pd.melt(df00,id_vars=["country"], var_name="year", value_name="life_exp").sort_values(["country", "year"], ascending = [True, True], ignore_index=True)

In [46]:
df00 #looks good

          country  year  life_exp
0     afghanistan  1990      52.6
1     afghanistan  1991      52.4
2     afghanistan  1992      52.9
3     afghanistan  1993      53.1
4     afghanistan  1994      52.7
...           ...   ...       ...
5231     zimbabwe  2013      56.8
5232     zimbabwe  2014      58.5
5233     zimbabwe  2015      59.6
5234     zimbabwe  2016      60.5
5235     zimbabwe  2017      61.4

[5236 rows x 3 columns]

In [47]:
#next, let's bring in the population table
df01 = pd.read_csv("data/gap_minder/gap_minder_population_total.csv")
df01

,country,1800,1801,1802,1803,1804,1805,1806,1807,1808,1809,1810,1811,1812,1813,1814,1815,1816,1817,1818,1819,1820,1821,1822,1823,1824,1825,1826,1827,1828,1829,1830,1831,1832,1833,1834,1835,1836,1837,1838,1839,1840,1841,1842,1843,1844,1845,1846,1847,1848,1849,1850,1851,1852,1853,1854,1855,1856,1857,1858,1859,1860,1861,1862,1863,1864,1865,1866,1867,1868,1869,1870,1871,1872,1873,1874,1875,1876,1877,1878,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1899,1900,1901,1902,1903,1904,1905,1906,1907,1908,1909,1910,1911,1912,1913,1914,1915,1916,1917,1918,1919,1920,1921,1922,1923,1924,1925,1926,1927,1928,1929,1930,1931,1932,1933,1934,1935,1936,1937,1938,1939,1940,1941,1942,1943,1944,1945,1946,1947,1948,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035,2036,2037,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047,2048,2049,2050,2051,2052,2053,2054,2055,2056,2057,2058,2059,2060,2061,2062,2063,2064,2065,2066,2067,2068,2069,2070,2071,2072,2073,2074,2075,2076,2077,2078,2079,2080,2081,2082,2083,2084,2085,2086,2087,2088,2089,2090,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
0,Afghanistan,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3280000,3290000,3300000,3310000,3320000,3340000,3350000,3370000,3380000,3400000,3410000,3430000,3450000,3460000,3480000,3490000,3510000,3520000,3540000,3550000,3570000,3590000,3600000,3620000,3630000,3650000,3670000,3680000,3700000,3720000,3730000,3750000,3770000,3790000,3810000,3830000,3840000,3860000,3880000,3900000,3920000,3940000,3960000,3980000,4000000,4020000,4040000,4060000,4080000,4100000,4120000,4140000,4160000,4180000,4210000,4230000,4250000,4270000,4290000,4310000,4330000,4350000,4380000,4400000,4420000,4440000,4460000,4490000,4510000,4530000,4550000,4580000,4600000,4620000,4650000,4670000,4690000,4710000,4740000,4760000,4790000,4830000,4880000,4940000,5000000,5060000,5130000,5200000,5260000,5330000,5470000,5680000,5980000,6360000,6850000,7370000,7920000,8520000,9170000,9880000,10300000,10600000,10500000,10300000,9710000,9200000,8720000,8260000,7830000,7420000,7100000,6870000,6720000,6640000,6640000,6640000,6640000,6640000,6640000,6640000,6660000,6700000,6770000,6850000,6950000,7060000,7170000,7280000,7390000,7500000,7620000,7750000,7840000,7940000,8040000,8150000,8270000,8400000,8540000,8680000,8830000,9000000,9170000,9350000,9540000,9740000,9960000,10200000,10400000,10600000,10900000,11200000,11500000,11800000,12100000,12400000,12700000,12900000,13200000,13300000,13400000,13400000,13200000,12900000,12500000,12200000,11900000,11700000,11600000,11600000,11900000,12400000,13300000,14500000,15800000,17100000,18100000,18900000,19400000,19700000,20200000,20800000,21600000,22600000,23700000,24700000,25700000,26400000,27100000,27700000,28400000,29200000,30100000,31200000,32300000,33400000,34400000,35400000,36300000,37200000,38000000,38900000,39800000,40800000,41700000,42600000,43500000,44400000,45400000,46300000,47200000,48100000,49000000,49900000,50800000,51700000,52600000,53500000,54300000,55200000,56100000,56900000,57700000,58600000,59400000,60200000,61000000,61700000,62500000,63200000,64000000,64700000,65400000,66100000,66700000,67400000,68000000,68600000,69200000,69800000,70300000,70800000,71400000,71800000,72300000,72800000,73200000,73600000,74000000,74300000,74700000,75000000,75300000,75500000,75800000,76000000,76200000,76400000,76500000,76700000,76800000,76900000,76900000,77000000,77000000,77000000,77000000,77000000,76900000,76900000,76800000,76700000,76600000,76400000,76300000,76100000,76000000,75800000,75600000,75400000,75200000,74900000
1,Albania,400000,402000,404000,405000,407000,409000,411000,413000,414000,416000,418000,420000,422000,424000,426000,427000,429000,431000,433000,435000,437000,439000,441000,443000,445000,447000,449000,451000,453000,455000,457000,459000,461000,463000,465000,467000,470000,472000,474000,476000,478000,480000,482000,485000,487000,489000,491000,493000,496000,498000,501000,505000,510000,515000,520000,525000,530000,535000,540000,545000,551000,556000,561000,567000,572000,578000,584000,589000,595000,601000,606000,612000,618000,624000,630000,636000,642000,648000,655000,661000,667000,674000,680000,687000,693000,700000,707000,714000,720000,727000,735000,742000,749000,757000,764000,772000,780000,788000,795000,803000,811000,819000,826000,834000,842000,849000,857000,865000,873000,881000,888000,895000,901000,907000,913000,919000,926000,932000,938000,944000,949000,955000,960000,965000,970000,975000,980000,985000,990000,997000,1000000,1010000,1020000,1030000,1040000,1050000,1060000,1080000,1090000,1100000,1110000,1120000,1140000,1150000,1160000,1180000,1190000,1210000,1220000,1240000,1260000,1290000,1320000,1350000,1380000,1420000,1460000,1500000,1540000,1590000,1640000,1690000,1740000,1790000,1840000,1900000,1950000,2000000,2050000,2100000,2150000,2200000,2250000,2310000,2360000,2410000,2460000,2520000,2570000,2630000,2680000,2740000,2790000,2840000,2900000,2970000,3040000,3120000,3200000,3260000,3290000,3280000,3250000,3200000,3150000,3110000,3100000,3100000,3110000,3120000,3130000,3130000,3130000,3120000,3100000,3090000,3060000,3030000,3000000,2970000,2950000,2930000,2910000,2900000,2900000,2890000,2890000,2880000,2880000,2880000,2880000,2870000,2870000,2860000,2850000,2840000,2830000,2820000,2810000,2800000,2790000,2770000,2760000,2750000,2740000,2720000,2710000,2690000,2670000,2650000,2630000,2620000,2600000,2580000,2550000,2530000,2510000,2490000,2470000,2450000,2420000,2400000,2380000,2360000,2330000,2310000,2290000,2260000,2240000,2210000,2190000,2170000,2140000,2120000,2090000,2070000,2040000,2020000,1990000,1970000,1940000,1920000,1890000,1860000,1830000,1810000,1780000,1750000,1720000,1690000,1660000,1630000,1600000,1570000,1540000,1510000,1480000,1450000,1420000,1390000,1360000,1330000,1300000,1270000,1250000,1220000,1190000,1170000,1140000,1110000,1090000
2,Algeria,2500000,2510000,2520000,2530000,2540000,2550000,2560000,2560000,2570000,2580000,2590000,2600000,2610000,2620000,2630000,2640000,2650000,2660000,2670000,2680000,2690000,2690000,2700000,2700000,2710000,2710000,2720000,2720000,2730000,2730000,2740000,2740000,2750000,2750000,2760000,2760000,2770000,2770000,2780000,2780000,2790000,2790000,2800000,2800000,2810000,2810000,2820000,2820000,2830000,2840000,2850000,2870000,2900000,2920000,2950000,2980000,3010000,3040000,3070000,3100000,3130000,3170000,3200000,3230000,3260000,3290000,3330000,3360000,3390000,3430000,3460000,3500000,3530000,3570000,3600000,3640000,3670000,3710000,3750000,3790000,3820000,3860000,3900000,3940000,3980000,4020000,4060000,4100000,4140000,4180000,4220000,4260000,4300000,4340000,4390000,4430000,4470000,4510000,4560000,4610000,4660000,4730000,4800000,4880000,4950000,5030000,5120000,5200000,5280000,5360000,5420000,5470000,5510000,5530000,5560000,5590000,5620000,5640000,5670000,5710000,5750000,5800000,5860000,5920000,5990000,6050000,6120000,6190000,6260000,6340000,6420000,6520000,6630000,6740000,6860000,6990000,7110000,7230000,7360000,7490000,7610000,7730000,7860000,7970000,8090000,8210000,8340000,8460000,8590000,8730000,8870000,9020000,9190000,9360000,9560000,9770000,10000000,10300000,10500000,10800000,11100000,11300000,11600000,11900000,12200000,12600000,12900000,13300000,13700000,14100000,14500000,14900000,15300000,15700000,16100000,16600000,17100000,17600000,18100000,18600000,19200000,19800000,20500000,21100000,21800000,22400000,23100000,23800000,24400000,25100000,25800000,26400000,27000000,27600000,28200000,28800000,29300000,29700000,30200000,30600000,31000000,31500000,31900000,32300000,32700000,33100000,33600000,34200000,34700000,35300000,36000000,36700000,37400000,38100000,38900000,39700000,40600000,41400000,42200000,43100000,43900000,44600000,45400000,46100000,46700000,47400000,48000000,48600000,49200000,49800000,50400000,50900000,51400000,52000000,52500000,53000000,53500000,54100000,54600000,55100000,55600000,56200000,56700000,57300000,57800000,58300000,58900000,59400000,59900000,60400000,60900000,61400000,61900000,62300000,62800000,63200000,63600000,64000000,64300000,64700000,65000000,65300000,65600000,65800000,66100000,66300000,66600000,66800000,67000000,67200000,67400000,67500000,67700000,67900000,68100000,68200000,68400000,68600000,68700000,68900000,69000000,69200000,69300000,69500000,69600000,69700000,69900000,70000000,70100000,70200000,70300000,70400000,70500000,70500000,70600000,70700000,70700000,70700000,70700000,70700000,70700000
3,Andorra,2650,2650,2650,2650,2650,2650,2650,2650,2650,2650,2650,2650,2650,2650,2650,2650,2650,2650,2650,2660,2660,2680,2690,2710,2730,2750,2770,2790,2810,2830,2850,2870,2890,2910,2930,2950,2970,2990,3010,3030,3060,3080,3100,3120,3140,3160,3190,3210,3230,3260,3280,3300,3320,3350,3370,3390,3420,3440,3460,3490,3510,3540,3560,3590,3610,3640,3660,3690,3710,3740,3760,3790,3820,3840,3870,3900,3920,3950,3980,4000,4030,4060,4090,4120,4140,4170,4200,4230,4260,4290,4320,4350,4380,4410,4440,4470,4500,4540,4570,4600,4630,4660,4690,4730,4760,4790,4820,4860,4890,4940,4990,5060,5140,5240,5330,5430,5530,5630,5740,5800,5820,5800,5740,5630,5530,5430,5330,5240,5140,5080,5040,5040,5060,5120,5170,5220,5280,5340,5390,5450,5510,5570,5630,5680,5750,5810,5870,5930,5990,6080,6200,6690,7250,7860,8530,9230,9980,10800,11600,12500,13400,14400,15400,16400,17500,18500,19600,20800,21900,23100,24300,25600,26900,28200,29500,30700,31800,32800,33700,34800,36100,37500,39100,40900,42700,44600,46500,48500,50400,52500,54500,56700,58900,61000,62700,63900,64400,64300,64100,64400,65400,67300,70000,73200,76200,78900,81000,82700,83900,84500,84500,83700,82400,80800,79200,78000,77300,77000,77000,77100,77300,77400,77500,77600,77700,77800,77900,77900,77900,77900,77900,77900,78000,78000,78000,78000,78000,78000,77900,77900,77900,77800,77700,77600,77500,77300,77100,76900,76700,76400,76100,75800,75400,75000,74600,74200,73800,73300,72800,72300,71800,71300,70800,70200,69700,69200,68700,68300,67800,67400,66900,66500,66200,65800,65500,65200,64900,64600,64400,64200,64000,63900,63700,63600,63500,63400,63300,63300,63200,63100,63100,63000,62900,62900,62800,62700,62700,62600,62500,62500,62400
4,Angola,1570000,1570000,1570000,1570000,1570000,1570000,1570000,1570000,1570000,1570000,1570000,1570000,1570000,1570000,1570000,1570000,1570000,1570000,1570000,1570000,1580000,1590000,1610000,1640000,1660000,1690000,1710000,1740000,1760000,1790000,1810000,1840000,1870000,1900000,1920000,1950000,1980000,2010000,2040000,2070000,2100000,2130000,2160000,2190000,2230000,2260000,2290000,2330000,2360000,2390000,2420000,2450000,2470000,2490000,2510000,2530000,2550000,2570000,2600000,2620000,2640000,2660000,2680000,2710000,2730000,2750000,2780000,2800000,2820000,2840000,2870000,2890000,2910000,2930000,2940000,2960000,2980000,3000000,3020000,3040000,3060000,3080000,3100000,3120000,3140000,3160000,3180000,3200000,3220000,3230000,3240000,3240000,3240000,3230000,3210000,3200000,3190000,3180000,3170000,3150000,3140000,3120000,3100000,3080000,3060000,3040000,3020000,3000000,2980000,2960000,2950000,2930000,2920000,2920000,2910000,2900000,2890000,2880000,2870000,2870000,2880000,2900000,2940000,2980000,3030000,3070000,3120000,3160000,3210000,3260000,3310000,3350000,3400000,3450000,3500000,3550000,3600000,3650000,3700000,3750000,3810000,3870000,3940000,4010000,4080000,4160000,4230000,4310000,4390000,4470000,4550000,4620000,4710000,4820000,4940000,5040000,5140000,5230000,5310000,5380000,5450000,5530000,5610000,5680000,5730000,5770000,5780000,5770000,5770000,5800000,5890000,6040000,6250000,6500000,6760000,7020000,7280000,7530000,7790000,8060000,8340000,8640000,8950000,9280000,9610000,9960000,10300000,10700000,11100000,11500000,11800000,12200000,12700000,13100000,13500000,13900000,14400000,14900000,15400000,15900000,16400000,16900000,17500000,18100000,18800000,19400000,20100000,20900000,21700000,22500000,23400000,24200000,25100000,26000000,26900000,27900000,28800000,29800000,30800000,31800000,32900000,33900000,35000000,36100000,37300000,38500000,39700000,40900000,42200000,43500000,44800000,46200000,47600000,49000000,50500000,52000000,53500000,55000000,56600000,58200000,59800000,61400000,63100000,64800000,66500000,68300000,70100000,71900000,73700000,75500000,77400000,79300000,81200000,83200000,85100000,87100000,89100000,91100000,93200000,95300000,97300000,99500000,102000000,104000000,106000000,108000000,110000000,112000000,115000000,117000000,119000000,121000000,124000000,126000000,128000000,131000000,133000000,135000000,137000000,140000000,142000000,144000000,147000000,149000000,151000000,154000000,156000000,158000000,161000000,163000000,165000000,168000000,170000000,172000000,175000000,177000000,179000000,182000000,184000000,186000000,188000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,1000000,978000,957000,936000,916000,896000,876000,857000,838000,820000,808000,795000,785000,776000,767000,759000,751000,742000,734000,731000,732000,738000,749000,765000,782000,798000,815000,833000,851000,871000,893000,918000,946000,977000,1010000,1040000,1070000,1110000,1150000,1180000,1200000,1220000,1240000,1250000,1260000,1270000,1280000,1290000,1300000,1310000,1330000,1340000,1360000,1370000,1390000,1410000,1430000,1440000,1460000,1480000,1500000,1520000,1540000,1550000,1570000,1590000,1610000,1630000,1650000,1680000,1700000,1730000,1760000,1790000,1820000,1850000,1890000,1920000,1960000,1990000,2020000,2050000,2080000,2110000,2150000,2180000,2210000,2240000,2270000,2300000,2340000,2370000,2410000,2440000,2480000,2510000,2550000,2590000,2630000,2660000,2700000,2730000,2760000,2790000,2820000,2860000,2890000,2920000,2950000,2980000,3010000,3040000,3060000,3090000,3110000,3130000,3160000,3180000,3200000,3230000,3250000,3280000,3310000,3340000,3380000,3410000,3440000,3480000,3510000,3550000,3590000,3630000,3680000,3730000,3780000,3830000,3890000,3940000,3990000,4060000,4140000,4240000,4340000,4470000,4590000,4730000,4860000,5000000,5140000,5300000,5480000,5730000,5970000,6230000,6480000,6740000,7010000,7290000,7560000,7850000,8140000,8440000,8740000,9050000,9370000,9690000,10000000,10400000,10700000,11000000,11400000,11700000,12100000,12500000,12800000,13200000,13600000,14000000,14400000,14800000,15200000,15600000,16000000,16400000,16900000,17300000,17800000,18200000,18700000,19200000,19600000,20100000,20600000,21000000,21500000,21900000,22400000,22800000,23300000,23700000,24200000,24600000,25100000,25600000,26000000,26400000,26900000,27200000,27600000,28000000,28400000,28900000,29400000,29800000,30000000,30100000,29900000,29400000,28900000,28500000,28400000,28700000,29300000,30000000,30800000,31500000,32000000,32500000,32900000,33300000,33600000,33900000,34200000,34400000,34700000,34900000,35100000,35300000,35500000,35700000,35800000,36000000,36100000,36300000,36400000,36500000,36600000,36700000,36800000,36900000,37000000,37100000,37200000,37200000,37300000,37400000,37400000,37500000,37500000,37500000,37500000,37600000,37600000,37600000,37600000,37600000,37500000,37500000,37500000,37500000,37400000,37400000,37300000,37300000,37200000,37100000,37100000,37000000,36900000,36800000,36700000,36600000,36500000,36400000,36300000,36200000,36100000,36000000,35900000,35700000,35600000,35500000,35400000,35200000,35100000,35000000,34800000,34700000,34500000,34400000,34200000
191,Vietnam,4000000,4100000,4200000,4310000,4410000,4530000,4640000,4750000,4870000,4990000,5120000,5250000,5380000,5520000,5650000,5790000,5940000,6090000,6240000,6360000,6440000,6500000,6510000,6490000,6470000,6460000,6440000,6420000,6400000,6380000,6360000,6340000,6320000,6310000,6290000,6270000,6250000,6230000,6210000,6200000,6180000,6160000,6140000,6120000,6110000,6090000,6070000,6050000,6040000,6060000,6110000,6210000,6350000,6530000,6710000,6900000,7100000,7300000,7500000,7720000,7930000,8160000,8390000,8620000,8870000,9120000,9380000,9640000,9910000,10100000,10300000,10400000,10500000,10600000,10600000,10600000,10600000,10700000,10700000,10700000,10800000,10800000,10800000,10800000,10900000,10900000,10900000,11000000,11000000,11000000,11000000,11100000,11100000,11100000,11200000,11200000,11200000,11300000,11300000,11400000,11700000,12100000,12600000,13300000,14000000,14700000,15500000,16300000,17200000,17900000,18400000,18700000,18900000,18800000,18700000,18600000,18500000,18400000,18300000,18300000,18200000,18100000,18000000,17900000,17900000,17800000,17700000,17600000,17500000,17500000,17500000,17500000,17600000,17800000,17900000,18000000,18100000,18200000,18400000,18600000,18900000,19300000,19800000,20300000,20900000,21600000,22200000,22800000,23500000,24200000,24800000,25400000,26000000,26600000,27400000,28100000,29000000,29800000,30800000,31700000,32700000,33700000,34700000,35700000,36800000,37900000,39000000,40100000,41200000,42300000,43400000,44500000,45500000,46600000,47700000,48700000,49800000,50900000,52000000,53100000,54300000,55500000,56800000,58100000,59500000,60900000,62300000,63700000,65100000,66600000,68000000,69400000,70900000,72300000,73700000,74900000,76100000,77100000,78100000,79000000,79900000,80700000,81500000,82300000,83100000,83800000,84600000,85400000,86200000,87100000,88000000,88900000,89800000,90800000,91700000,92700000,93600000,94600000,95500000,96500000,97300000,98200000,99000000,99700000,100000000,101000000,102000000,102000000,103000000,104000000,104000000,105000000,105000000,106000000,106000000,106000000,107000000,107000000,107000000,108000000,108000000,108000000,108000000,109000000,109000000,109000000,109000000,109000000,109000000,110000000,110000000,110000000,110000000,110000000,110000000,110000000,110000000,110000000,110000000,109000000,109000000,109000000,109000000,109000000,109000000,108000000,108000000,108000000,108000000,107000000,107000000,107000000,106000000,106000000,106000000,106000000,105000000,105000000,105000000,104000000,104000000,104000000,103000000,103000000,103000000,102000000,102000000,102000000,101000000,101000000,101000000,100000000,100000000,99700000,99400000,99100000,98800000,98400000,98100000,97800000,97400000

In [48]:
#removing years outside our dataframe
df01 = df01.drop(df01.columns.to_series()["1800":"1989"], axis=1)
df01 = df01.drop(df01.columns.to_series()["2018":], axis=1)

In [49]:
df01.head()

,country,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Afghanistan,12400000,13300000,14500000,15800000,17100000,18100000,18900000,19400000,19700000,20200000,20800000,21600000,22600000,23700000,24700000,25700000,26400000,27100000,27700000,28400000,29200000,30100000,31200000,32300000,33400000,34400000,35400000,36300000
1,Albania,3290000,3280000,3250000,3200000,3150000,3110000,3100000,3100000,3110000,3120000,3130000,3130000,3130000,3120000,3100000,3090000,3060000,3030000,3000000,2970000,2950000,2930000,2910000,2900000,2900000,2890000,2890000,2880000
2,Algeria,25800000,26400000,27000000,27600000,28200000,28800000,29300000,29700000,30200000,30600000,31000000,31500000,31900000,32300000,32700000,33100000,33600000,34200000,34700000,35300000,36000000,36700000,37400000,38100000,38900000,39700000,40600000,41400000
3,Andorra,54500,56700,58900,61000,62700,63900,64400,64300,64100,64400,65400,67300,70000,73200,76200,78900,81000,82700,83900,84500,84500,83700,82400,80800,79200,78000,77300,77000
4,Angola,11800000,12200000,12700000,13100000,13500000,13900000,14400000,14900000,15400000,15900000,16400000,16900000,17500000,18100000,18800000,19400000,20100000,20900000,21700000,22500000,23400000,24200000,25100000,26000000,26900000,27900000,28800000,29800000

In [50]:
df01 = df01.applymap(lambda s:s.lower() if type(s) == str else s) #lowercasing

In [51]:
df01 = pd.melt(df01,id_vars=["country"], var_name="year", value_name="total_pop").sort_values(["country", "year"], ascending = [True, True], ignore_index=True)

In [52]:
df01

          country  year  total_pop
0     afghanistan  1990   12400000
1     afghanistan  1991   13300000
2     afghanistan  1992   14500000
3     afghanistan  1993   15800000
4     afghanistan  1994   17100000
...           ...   ...        ...
5455     zimbabwe  2013   13400000
5456     zimbabwe  2014   13600000
5457     zimbabwe  2015   13800000
5458     zimbabwe  2016   14000000
5459     zimbabwe  2017   14200000

[5460 rows x 3 columns]

In [53]:
#next, gdp per capita

In [54]:
df02 = pd.read_csv("data/gap_minder/gap_minder_gdppercapita_us_inflation_adjusted.csv")
df02

,country,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,330.0,343.0,333.0,357.0,365.0,406.0,412.0,488.0,543,529.0,576.0,588.0,584.0,574.0,571.0,572.0,568.0,571.0
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1990.0,2060.0,2080.0,2060.0,1990.0,1990.0,2060.0,2000.0,1940.0,2070.0,1840.0,1330.0,1240.0,1370.0,1490.0,1700.0,1870.0,1680.0,1840.0,2090.0,2240.0,2450.0,2570.0,2730.0,2890.0,3060.0,3260.0,3490.0,3780.0,3930.0,4090,4210.0,4280.0,4330.0,4410.0,4520.0,4680.0,4860.0,5070.0,5210.0
2,Algeria,2480.0,2090.0,1640.0,2150.0,2210.0,2290.0,2120.0,2260.0,2430.0,2560.0,2710.0,2340.0,2900.0,2930.0,3060.0,3120.0,3290.0,3370.0,3570.0,3730.0,3640.0,3640.0,3750.0,3830.0,3930.0,3950.0,3850.0,3720.0,3580.0,3640.0,3570.0,3440.0,3420.0,3280.0,3180.0,3240.0,3320.0,3300.0,3410.0,3470.0,3560.0,3620.0,3770.0,3990.0,4110.0,4290.0,4300.0,4380.0,4410.0,4400.0,4480,4520.0,4590.0,4620.0,4700.0,4780.0,4830.0,4790.0,4760.0,4710.0
3,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41700.0,41400.0,42600.0,43700.0,44200.0,42700.0,42600.0,42500.0,41900.0,40600.0,40100.0,38500.0,37400.0,36400.0,35500.0,34700.0,34400.0,34800.0,35200.0,35500.0,35400.0,34900.0,33900.0,32400.0,32300.0,32600.0,33800.0,36900.0,38200.0,39600.0,40400.0,42400.0,42600.0,44300.0,46000.0,46900.0,47800.0,47600.0,44300.0,41700.0,40900,41200.0,39800.0,39100.0,40900.0,42100.0,44100.0,44400.0,45100.0,45900.0
4,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3180.0,2930.0,2830.0,2850.0,2910.0,2910.0,2890.0,2900.0,2980.0,2880.0,2690.0,2620.0,2390.0,1760.0,1730.0,1920.0,2110.0,2200.0,2230.0,2200.0,2200.0,2210.0,2430.0,2420.0,2600.0,2880.0,3100.0,3410.0,3650.0,3550.0,3590,3580.0,3750.0,3800.0,3840.0,3750.0,3530.0,3410.0,3230.0,3100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,Venezuela,12500.0,12400.0,13000.0,13000.0,14000.0,14100.0,13800.0,13800.0,14300.0,14000.0,14600.0,14300.0,14100.0,14700.0,14600.0,14600.0,15200.0,15700.0,15700.0,15300.0,14300.0,13800.0,13200.0,12400.0,12200.0,11900.0,12400.0,12500.0,12900.0,11500.0,12000.0,12800.0,13300.0,13000.0,12500.0,12700.0,12400.0,12900.0,12700.0,11700.0,11900.0,12100.0,10800.0,9830.0,11400.0,12400.0,13400.0,14400.0,14900.0,14200.0,13800,14200.0,14700.0,14700.0,14000.0,NaN,NaN,NaN,NaN,NaN
187,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,378.0,383.0,385.0,390.0,401.0,421.0,433.0,450.0,478.0,507.0,542.0,583.0,628.0,670.0,700.0,724.0,765.0,804.0,847.0,897.0,955.0,1020.0,1080.0,1150.0,1200.0,1250.0,1320,1390.0,1440.0,1510.0,1580.0,1670.0,1750.0,1850.0,1960.0,2080.0
188,Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,1010.0,1040.0,1030.0,1050.0,1060.0,1070.0,1090.0,1120.0,1130.0,1170.0,1180.0,1190.0,1200.0,1210.0,1240.0,1250.0,1250.0,1260.0,1270.0,1330,1130.0,1130.0,1150.0,1120.0,785.0,694.0,643.0,633.0,NaN
189,Zambia,1500.0,1470.0,1390.0,1400.0,1520.0,1720.0,1570.0,1650.0,1620.0,1560.0,1580.0,1530.0,1610.0,1550.0,1590.0,1500.0,1540.0,1420.0,1380.0,1300.0,1290.0,1330.0,1250.0,1180.0,1140.0,1120.0,1090.0,1090.0,1120.0,1080.0,1040.0,1020.0,975.0,1020.0,907.0,910.0,941.0,951.0,921.0,938.0,949.0,973.0,991.0,1030.0,1080.0,1130.0,1180.0,1250.0,1310.0,1390.0,1490,1530.0,1590.0,1620.0,1640.0,1640.0,1650.0,1660.0,1680.0,1660.0
190,Zimbabwe,995.0,1020.0,1000.0,1030.0,985.0,999.0,981.0,1030.0,1010.0,1100.0,1310.0,1370.0,1440.0,1420.0,1460.0,1390.0,1350.0,1220.0,1150.0,1150.0,1270.0,1380.0,1360.0,1340.0,1260.0,1300.0,1280.0,1250.0,1310.0,1330.0,1390.0,1430.0,1270.0,1270.0,1360.0,1350.0,1470.0,1490.0,1520.0,1500.0,1450.0,1460.0,1330.0,1100.0,1030.0,971.0,932.0,890.0,726.0,803.0,948,1070.0,1220.0,1230.0,1230.0,1230.0,1220.0,1260.0,1310.0,1180.0

In [55]:
#refocus timeframe
df02 = df02.drop(df02.columns.to_series()["1960":"1989"], axis=1)
df02 = df02.drop(df02.columns.to_series()["2018":], axis=1)

In [56]:
df02 = df02.applymap(lambda s:s.lower() if type(s) == str else s) #lowercasing

In [57]:
#pivoting
df02 = pd.melt(df02,id_vars=["country"], var_name="year", value_name="gdp_cap").sort_values(["country", "year"], ascending = [True, True], ignore_index=True)

In [58]:
df02

          country  year  gdp_cap
0     afghanistan  1990      NaN
1     afghanistan  1991      NaN
2     afghanistan  1992      NaN
3     afghanistan  1993      NaN
4     afghanistan  1994      NaN
...           ...   ...      ...
5343     zimbabwe  2013   1230.0
5344     zimbabwe  2014   1230.0
5345     zimbabwe  2015   1230.0
5346     zimbabwe  2016   1220.0
5347     zimbabwe  2017   1260.0

[5348 rows x 3 columns]

In [59]:
#next, let's import access to basic sanitation and go through all the setps

In [60]:
df03 = pd.read_csv("data/gap_minder/gap_minder_at_least_basic_sanitation_overall_access_percent.csv")
df03

,country,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Afghanistan,0.235,0.235,0.246,0.258,0.269,0.280,0.292,0.304,0.317,0.329,0.342,0.355,0.367,0.381,0.394,0.407,0.421,0.434
1,Albania,0.883,0.891,0.899,0.907,0.914,0.922,0.929,0.936,0.943,0.949,0.956,0.962,0.968,0.973,0.977,0.977,0.977,0.977
2,Algeria,0.837,0.841,0.844,0.847,0.850,0.853,0.856,0.858,0.861,0.863,0.866,0.868,0.870,0.872,0.873,0.875,0.875,0.876
3,Andorra,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
4,Angola,0.276,0.290,0.304,0.319,0.333,0.347,0.360,0.373,0.385,0.398,0.411,0.423,0.436,0.449,0.461,0.474,0.486,0.499
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Venezuela,NaN,NaN,NaN,NaN,NaN,0.925,0.929,0.932,0.936,0.939,0.939,0.939,0.939,0.939,0.939,0.939,0.939,0.939
190,Vietnam,0.524,0.542,0.561,0.580,0.598,0.617,0.636,0.654,0.673,0.692,0.710,0.729,0.747,0.765,0.783,0.801,0.819,0.835
191,Yemen,0.421,0.424,0.427,0.442,0.456,0.469,0.481,0.493,0.505,0.517,0.529,0.541,0.552,0.563,0.574,0.585,0.588,0.591
192,Zambia,0.237,0.238,0.240,0.242,0.243,0.245,0.247,0.249,0.250,0.252,0.253,0.255,0.256,0.257,0.259,0.260,0.261,0.264
193,Zimbabwe,0.459,0.461,0.462,0.461,0.454,0.446,0.439,0.432,0.425,0.418,0.411,0.403,0.396,0.389,0.383,0.376,0.369,0.362

In [61]:
df03 = df03.applymap(lambda s:s.lower() if type(s) == str else s)

In [62]:
#pivoting
df03 = pd.melt(df03,id_vars=["country"], var_name="year", value_name="sanit_access").sort_values(["country", "year"], ascending = [True, True], ignore_index=True)

In [63]:
df03

          country  year  sanit_access
0     afghanistan  2000         0.235
1     afghanistan  2001         0.235
2     afghanistan  2002         0.246
3     afghanistan  2003         0.258
4     afghanistan  2004         0.269
...           ...   ...           ...
3487     zimbabwe  2013         0.389
3488     zimbabwe  2014         0.383
3489     zimbabwe  2015         0.376
3490     zimbabwe  2016         0.369
3491     zimbabwe  2017         0.362

[3492 rows x 3 columns]

In [64]:
#next, let's import access to basic water access and go through all the setps

In [65]:
df04 = pd.read_csv("data/gap_minder/gap_minder_at_least_basic_water_source_overall_access_percent.csv")
df04

,country,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Afghanistan,0.278,0.278,0.299,0.320,0.341,0.363,0.384,0.408,0.433,0.458,0.484,0.509,0.535,0.562,0.588,0.615,0.643,0.671
1,Albania,0.879,0.879,0.879,0.879,0.879,0.879,0.879,0.879,0.879,0.879,0.878,0.878,0.879,0.895,0.910,0.910,0.910,0.910
2,Algeria,0.898,0.901,0.904,0.907,0.909,0.912,0.914,0.917,0.919,0.922,0.924,0.926,0.928,0.931,0.933,0.935,0.935,0.936
3,Andorra,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
4,Angola,0.411,0.423,0.434,0.444,0.454,0.463,0.472,0.480,0.488,0.496,0.504,0.512,0.520,0.528,0.535,0.543,0.551,0.558
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Venezuela,0.967,0.966,0.965,0.965,0.964,0.964,0.963,0.963,0.962,0.962,0.961,0.961,0.960,0.959,0.959,0.958,0.958,0.957
190,Vietnam,0.801,0.810,0.819,0.828,0.836,0.845,0.853,0.862,0.870,0.878,0.887,0.895,0.903,0.910,0.923,0.932,0.940,0.947
191,Yemen,0.378,0.381,0.383,0.403,0.423,0.443,0.463,0.482,0.502,0.521,0.540,0.559,0.577,0.596,0.614,0.632,0.633,0.635
192,Zambia,0.495,0.500,0.507,0.514,0.521,0.527,0.533,0.540,0.546,0.552,0.558,0.564,0.570,0.576,0.581,0.587,0.592,0.600
193,Zimbabwe,0.717,0.719,0.716,0.711,0.706,0.701,0.696,0.690,0.685,0.680,0.675,0.670,0.665,0.660,0.655,0.650,0.645,0.641

In [66]:
df04 = df04.applymap(lambda s:s.lower() if type(s) == str else s) #lowercase

In [67]:
#pivoting
df04 = pd.melt(df04,id_vars=["country"], var_name="year", value_name="water_access").sort_values(["country", "year"], ascending = [True, True], ignore_index=True)

In [68]:
df04

          country  year  water_access
0     afghanistan  2000         0.278
1     afghanistan  2001         0.278
2     afghanistan  2002         0.299
3     afghanistan  2003         0.320
4     afghanistan  2004         0.341
...           ...   ...           ...
3487     zimbabwe  2013         0.660
3488     zimbabwe  2014         0.655
3489     zimbabwe  2015         0.650
3490     zimbabwe  2016         0.645
3491     zimbabwe  2017         0.641

[3492 rows x 3 columns]

In [69]:
#next, doctors per 1000 people

In [70]:
df05 = pd.read_csv("data/gap_minder/gap_minder_medical_doctors_per_1000_people.csv")
df05

,country,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Afghanistan,0.035,NaN,NaN,NaN,NaN,0.063,NaN,NaN,NaN,NaN,0.065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.077,NaN,NaN,NaN,NaN,0.183,0.179,NaN,0.129,0.109,NaN,NaN,0.143,NaN,NaN,NaN,0.1100,NaN,NaN,NaN,0.190,NaN,NaN,NaN,NaN,0.1600,0.1740,0.1740,0.2130,0.2360,0.2520,0.2410,0.2850,0.298,0.285,0.278,NaN,NaN
1,Albania,0.276,NaN,NaN,NaN,NaN,0.481,NaN,NaN,NaN,NaN,0.739,0.911,0.845,NaN,NaN,NaN,NaN,1.04,NaN,NaN,1.370,NaN,NaN,1.42,1.410,1.410,NaN,NaN,NaN,NaN,1.370,1.460,1.620,1.410,1.34,1.360,1.38,1.3900,1.39,1.280,1.380,1.310,1.170,1.19,1.1900,NaN,1.1800,1.2000,NaN,1.2300,1.2300,1.2200,1.2700,1.2800,NaN,NaN,1.220,NaN,NaN
2,Algeria,0.173,NaN,NaN,NaN,NaN,0.116,NaN,NaN,NaN,NaN,0.123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.38,NaN,NaN,NaN,NaN,0.427,NaN,NaN,NaN,0.429,NaN,0.942,NaN,NaN,0.821,NaN,0.846,NaN,NaN,1.00,NaN,NaN,NaN,1.110,NaN,NaN,1.0200,NaN,1.2000,NaN,NaN,1.2100,NaN,NaN,NaN,NaN,NaN,1.830,1.790,1.72
3,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.240,NaN,2.4600,2.53,2.590,2.570,2.600,2.900,3.33,3.1300,3.2300,3.0100,3.0100,NaN,3.1500,4.0000,NaN,NaN,NaN,NaN,3.330,NaN,NaN,NaN
4,Angola,0.067,NaN,NaN,NaN,NaN,0.076,NaN,NaN,NaN,NaN,0.116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.059,NaN,NaN,NaN,NaN,NaN,0.042,NaN,NaN,NaN,NaN,NaN,NaN,0.0592,NaN,NaN,NaN,NaN,NaN,NaN,0.0621,NaN,NaN,NaN,NaN,0.1310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.215,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,Venezuela,0.666,NaN,NaN,NaN,NaN,0.815,NaN,NaN,NaN,NaN,0.883,NaN,NaN,NaN,0.904,0.904,0.904,NaN,NaN,NaN,0.830,0.996,0.833,NaN,1.440,1.200,1.400,1.400,1.600,1.690,1.560,NaN,NaN,NaN,NaN,1.940,NaN,NaN,NaN,NaN,NaN,1.950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.241,0.247,NaN,NaN,NaN,NaN,1.060,NaN,NaN,0.391,0.404,0.407,0.437,NaN,NaN,NaN,NaN,0.5690,0.48,0.515,NaN,0.524,0.551,NaN,NaN,0.6140,0.6240,0.6410,0.6650,0.6980,0.7100,1.1500,0.8210,1.1800,0.783,0.796,0.828,NaN,NaN
189,Yemen,0.023,NaN,NaN,NaN,NaN,0.032,NaN,NaN,NaN,NaN,0.029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.145,NaN,NaN,NaN,0.171,NaN,NaN,NaN,NaN,0.007,NaN,NaN,NaN,NaN,0.247,0.23,0.2390,0.20,NaN,NaN,0.219,NaN,NaN,0.3450,NaN,NaN,NaN,0.3160,0.3170,NaN,NaN,NaN,NaN,0.525,NaN,NaN,NaN,NaN
190,Zambia,0.107,NaN,NaN,NaN,NaN,0.088,NaN,NaN,NaN,NaN,0.073,NaN,NaN,NaN,NaN,0.074,NaN,NaN,NaN,NaN,0.076,0.126,NaN,0.14,NaN,0.141,NaN,NaN,NaN,NaN,0.092,NaN,NaN,NaN,NaN,0.069,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1300,0.0545,0.0533,NaN,0.0619,0.0606,0.0614,0.1650,0.1660,NaN,NaN,NaN,0.163,NaN,1.19
191,Zimbabwe,0.202,NaN,NaN,NaN,NaN,0.125,NaN,NaN,NaN,NaN,0.162,NaN,NaN,NaN,NaN,0.158,NaN,NaN,NaN,NaN,0.161,0.139,NaN,NaN,NaN,NaN,NaN,0.135,NaN,NaN,0.127,NaN,NaN,NaN,NaN,0.143,NaN,NaN,NaN,NaN,0.126,NaN,0.057,NaN,0.1730,0.1260,NaN,0.0544,0.0596,0.1210,0.1270,0.0817,0.0807,0.0834,0.124,0.181,0.179,0.186,0.21

In [71]:
#removing years outside our dataframe
df05 = df05.drop(df05.columns.to_series()["1960":"1989"], axis=1)
df05 = df05.drop(df05.columns.to_series()["2018":], axis=1)

In [72]:
df05 = df05.applymap(lambda s:s.lower() if type(s) == str else s) #lowercasing

In [73]:
df05 = pd.melt(df05,id_vars=["country"], var_name="year", value_name="dr_per_1000").sort_values(["country", "year"], ascending = [True, True], ignore_index=True)

In [74]:
df05

          country  year  dr_per_1000
0     afghanistan  1990       0.1090
1     afghanistan  1991          NaN
2     afghanistan  1992          NaN
3     afghanistan  1993       0.1430
4     afghanistan  1994          NaN
...           ...   ...          ...
5371     zimbabwe  2013       0.0834
5372     zimbabwe  2014       0.1240
5373     zimbabwe  2015       0.1810
5374     zimbabwe  2016       0.1790
5375     zimbabwe  2017       0.1860

[5376 rows x 3 columns]

In [75]:
#next, child mortality below the age of 5

In [76]:
df06 = pd.read_csv("data/gap_minder/gap_minder_child_mortality_0_5_year_olds_dying_per_1000_born.csv")
df06

,country,1800,1801,1802,1803,1804,1805,1806,1807,1808,1809,1810,1811,1812,1813,1814,1815,1816,1817,1818,1819,1820,1821,1822,1823,1824,1825,1826,1827,1828,1829,1830,1831,1832,1833,1834,1835,1836,1837,1838,1839,1840,1841,1842,1843,1844,1845,1846,1847,1848,1849,1850,1851,1852,1853,1854,1855,1856,1857,1858,1859,1860,1861,1862,1863,1864,1865,1866,1867,1868,1869,1870,1871,1872,1873,1874,1875,1876,1877,1878,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1899,1900,1901,1902,1903,1904,1905,1906,1907,1908,1909,1910,1911,1912,1913,1914,1915,1916,1917,1918,1919,1920,1921,1922,1923,1924,1925,1926,1927,1928,1929,1930,1931,1932,1933,1934,1935,1936,1937,1938,1939,1940,1941,1942,1943,1944,1945,1946,1947,1948,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035,2036,2037,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047,2048,2049,2050,2051,2052,2053,2054,2055,2056,2057,2058,2059,2060,2061,2062,2063,2064,2065,2066,2067,2068,2069,2070,2071,2072,2073,2074,2075,2076,2077,2078,2079,2080,2081,2082,2083,2084,2085,2086,2087,2088,2089,2090,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
0,Afghanistan,469.0,469.0,469.0,469.0,469.0,469.0,470.0,470.0,470.0,470.0,470.0,470.0,470.0,470.0,470.0,470.0,471.0,471.0,471.0,471.0,471.0,471.0,471.0,471.0,471.0,471.0,473.0,473.0,473.0,473.0,473.0,473.0,473.0,473.0,473.0,473.0,474.0,474.0,474.0,474.0,474.0,474.0,474.0,474.0,474.0,476.0,476.0,476.0,476.0,476.0,476.0,476.0,476.0,476.0,476.0,477.0,477.0,477.0,477.0,477.0,477.0,477.0,477.0,477.0,477.0,479.0,479.0,479.0,479.0,479.0,479.0,479.0,479.0,479.0,479.0,480.0,480.0,480.0,480.0,480.0,480.0,480.0,480.0,480.0,480.0,481.0,481.0,481.0,481.0,481.0,481.0,481.0,481.0,481.0,483.0,483.0,483.0,483.0,482.0,482.0,482.0,481.0,481.0,480.0,481.0,480.0,480.0,479.0,478.0,477.0,476.0,475.0,473.0,472.0,473.0,471.0,470.0,469.0,468.0,467.0,466.0,465.0,463.0,462.0,463.0,461.0,460.0,459.0,458.0,457.0,456.0,454.0,451.0,451.0,448.0,446.0,444.0,442.0,440.0,438.0,436.0,434.0,431.0,431.0,428.0,426.0,424.0,422.0,420.0,418.0,416.0,413.0,407.0,401.0,395.0,389.0,383.0,376.0,370.0,363.0,357.0,351.0,345.0,340.0,335.0,330.0,324.0,319.0,314.0,308.0,303.0,297.0,292.0,286.0,280.0,275.0,269.0,263.0,257.0,250.0,244.0,238.0,231.0,225.0,218.0,211.0,205.0,198.0,192.0,185.0,179.0,173.0,167.00,161.00,156.00,151.00,146.00,142.00,138.00,133.00,129.00,125.00,121.00,117.00,113.00,109.00,104.00,100.00,96.00,91.90,88.00,84.10,80.50,77.00,73.50,70.40,67.50,64.70,62.30,60.10,58.10,56.10,54.20,52.40,50.60,49.00,47.50,46.00,44.60,43.30,42.00,40.90,39.70,38.70,37.60,36.70,35.70,34.80,34.00,33.10,32.30,31.60,30.80,30.10,29.50,28.90,28.30,27.70,27.10,26.60,26.00,25.50,25.00,24.50,24.00,23.50,23.10,22.60,22.20,21.80,21.40,21.00,20.60,20.20,19.90,19.50,19.10,18.80,18.40,18.10,17.80,17.40,17.10,16.80,16.60,16.30,16.00,15.80,15.50,15.20,15.00,14.80,14.50,14.30,14.10,13.80,13.60,13.40,13.20,12.90,12.80,12.60,12.40,12.20,12.00,11.80,11.60,11.50,11.30,11.10,11.10
1,Albania,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,375.0,374.0,374.0,374.0,373.0,373.0,372.0,372.0,371.0,370.0,369.0,369.0,368.0,367.0,366.0,365.0,364.0,363.0,362.0,362.0,361.0,360.0,359.0,358.0,357.0,356.0,355.0,355.0,354.0,353.0,352.0,348.0,344.0,341.0,337.0,333.0,330.0,326.0,323.0,319.0,316.0,312.0,309.0,305.0,302.0,299.0,296.0,292.0,289.0,286.0,283.0,280.0,269.0,258.0,248.0,239.0,229.0,220.0,211.0,203.0,195.0,188.0,180.0,173.0,166.0,160.0,153.0,147.0,142.0,136.0,131.0,126.0,121.0,116.0,111.0,107.0,104.0,100.0,97.4,95.3,87.7,80.8,74.5,68.6,63.4,58.7,54.6,51.0,47.9,45.1,42.7,40.7,38.9,37.40,35.90,34.50,33.20,31.70,30.30,28.80,27.40,25.90,24.50,23.10,21.80,20.40,19.20,17.90,16.70,15.50,14.40,13.30,12.30,11.40,10.70,10.10,9.60,9.27,9.02,8.82,8.68,8.52,8.36,8.19,8.01,7.83,7.65,7.45,7.24,7.04,6.83,6.63,6.43,6.25,6.08,5.92,5.78,5.65,5.52,5.40,5.28,5.17,5.05,4.94,4.83,4.73,4.62,4.52,4.43,4.33,4.24,4.15,4.07,3.99,3.92,3.85,3.79,3.72,3.67,3.61,3.55,3.50,3.45,3.40,3.35,3.30,3.25,3.20,3.16,3.11,3.07,3.03,2.98,2.94,2.90,2.87,2.83,2.79,2.76,2.72,2.68,2.65,2.62,2.59,2.55,2.52,2.49,2.46,2.44,2.41,2.38,2.35,2.32,2.30,2.27,2.24,2.22,2.19,2.16,2.14,2.11,2.11
2,Algeria,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,460.0,459.0,459.0,458.0,458.0,457.0,457.0,456.0,455.0,454.0,453.0,452.0,451.0,450.0,449.0,448.0,447.0,446.0,445.0,443.0,442.0,441.0,440.0,439.0,438.0,433.0,429.0,426.0,421.0,417.0,412.0,409.0,403.0,396.0,391.0,384.0,378.0,370.0,364.0,358.0,351.0,345.0,339.0,337.0,334.0,331.0,318.0,305.0,292.0,280.0,269.0,258.0,256.0,251.0,247.0,243.0,243.0,243.0,243.0,242.0,242.0,243.0,243.0,243.0,244.0,246.0,246.0,247.0,247.0,246.0,244.0,240.0,235.0,229.0,222.0,213.0,204.0,194.0,184.0,173.0,162.0,149.0,134.0,118.0,102.0,87.0,74.4,65.0,58.5,54.2,51.4,49.5,48.2,47.00,46.00,44.80,43.60,42.50,41.60,40.80,40.30,39.70,38.90,37.80,36.50,35.00,33.50,32.00,30.70,29.40,28.30,27.40,26.70,26.10,25.70,25.30,24.90,24.50,24.00,23.50,22.80,22.20,21.60,20.90,20.40,19.80,19.20,18.60,18.10,17.60,17.10,16.60,16.10,15.70,15.20,14.80,14.40,14.00,13.60,13.30,12.90,12.60,12.30,11.90,11.60,11.30,11.00,10.80,10.50,10.20,9.96,9.71,9.47,9.24,9.01,8.80,8.59,8.38,8.19,8.00,7.81,7.64,7.46,7.30,7.14,6.99,6.84,6.69,6.56,6.42,6.29,6.17,6.04,5.93,5.82,5.71,5.60,5.50,5.41,5.32,5.23,5.14,5.05,4.97,4.89,4.81,4.73,4.65,4.57,4.50,4.42,4.35,4.28,4.20,4.14,4.07,4.00,3.94,3.88,3.82,3.76,3.76
3,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.9,74.0,68.2,62.8,57.9,53.4,49.2,45.5,42.2,39.2,36.6,34.5,32.6,31.0,29.6,28.5,27.5,26.6,25.9,25.1,24.4,23.7,22.9,22.2,21.4,20.7,19.9,19.1,18.3,17.5,16.8,16.2,15.6,15.2,14.8,14.6,13.7,12.9,12.2,11.5,10.8,10.2,9.63,9.09,8.58,8.11,7.69,7.32,6.97,6.68,6.41,6.16,5.93,5.71,5.49,5.27,5.05,4.84,4.62,4.39,4.18,3.98,3.79,3.61,3.43,3.27,3.14,3.01,2.89,2.87,2.85,2.82,2.79,2.77,2.75,2.72,2.67,2.62,2.57,2.52,2.47,2.43,2.38,2.33,2.28,2.24,2.20,2.15,2.11,2.07,2.03,2.00,1.96,1.92,1.89,1.86,1.82,1.79,1.76,1.73,1.70,1.67,1.64,1.61,1.58,1.56,1.53,1.50,1.47,1.45,1.43,1.40,1.38,1.35,1.33,1.31,1.29,1.27,1.25,1.23,1.21,1.18,1.17,1.15,1.13,1.11,1.09,1.08,1.06,1.04,1.02,1.01,0.99,0.97,0.96,0.94,0.93,0.91,0.90,0.88,0.87,0.86,0.84,0.83,0.81,0.80,0.79,0.78,0.77,0.76,0.76
4,Angola,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,486.0,485.0,485.0,485.0,485.0,484.0,484.0,483.0,483.0,482.0,481.0,480.0,479.0,478.0,477.0,476.0,475.0,474.0,473.0,471.0,470.0,469.0,468.0,467.0,466.0,465.0,463.0,462.0,461.0,460.0,459.0,458.0,457.0,455.0,454.0,449.0,444.0,439.0,434.0,428.0,423.0,418.0,413.0,408.0,403.0,396.0,388.0,381.0,373.0,366.0,359.0,352.0,344.0,338.0,331.0,330.0,329.0,327.0,324.0,322.0,320.0,317.0,314.0,312.0,308.0,305.0,302.0,298.0,295.0,291.0,287.0,283.0,279.0,275.0,271.0,267.0,263.0,260.0,256.0,252.0,249.0,246.0,243.0,241.0,238.0,236.0,232.0,230.0,228.0,226.0,225.0,224.0,223.0,223.0,223.0,224.0,224.00,224.00,224.00,223.00,221.00,219.00,215.00,211.00,206.00,200.00,193.00,185.00,176.00,167.00,157.00,148.00,138.00,129.00,120.00,113.00,105.00,98.40,92.90,88.10,84.00,80.40,77.20,74.50,72.30,70.40,68.60,67.00,65.40,63.70,62.00,60.30,58.70,57.20,55.70,54.20,52.80,51.40,50.10,48.80,47.50,46.30,45.20,44.00,43.00,42.00,41.00,40.00,39.10,38.20,37.30,36.50,35.60,34.90,34.10,33.40,32.60,32.00,31.30,30.70,30.00,29.40,28.90,28.30,27.80,27.20,26.70,26.30,25.80,25.40,24.90,24.50,24.10,23.70,23.40,23.00,22.60,22.30,21.90,21.60,21.30,21.00,20.80,20.50,20.20,20.00,19.70,19.50,19.20,19.00,18.80,18.60,18.30,18.10,17.90,17.70,17.50,17.30,17.10,17.00,16.80,16.60,16.40,16.30,16.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,415.0,414.0,414.0,414.0,413.0,413.0,412.0,412.0,411.0,410.0,409.0,408.0,408.0,407.0,406.0,405.0,404.0,403.0,402.0,401.0,400.0,399.0,398.0,379.0,360.0,343.0,326.0,311.0,296.0,281.0,268.0,255.0,242.0,253.0,258.0,264.0,257.0,218.0,213.0,215.0,222.0,209.0,190.0,188.0,177.0,166.0,181.0,147.0,153.0,149.0,146.0,133.0,107.0,116.0,111.0,106.0,101.0,97.0,93.0,89.1,85.5,82.2,79.2,76.6,74.4,72.6,71.0,69.6,68.3,66.9,65.5,64.0,62.3,60.5,58.6,56.9,55.1,53.3,51.6,49.8,47.8,45.9,43.9,42.0,40.3,38.7,37.3,36.0,34.7,33.4,32.1,30.8,29.6,28.5,27.80,27.20,26.70,26.20,25.50,24.50,23.50,27.50,21.60,20.90,20.30,19.80,19.10,18.50,17.90,17.40,17.10,17.00,17.00,17.10,17.20,17.30,17.30,19.40,24.50,24.50,24.50,25.30,25.50,25.30,24.60,23.80,22.80,21.80,20.90,20.00,19.20,18.50,18.00,17.50,17.10,16.70,16.40,16.00,15.60,15.30,14.90,14.60,14.20,13.90,13.60,13.30,13.00,12.70,12.40,12.10,11.80,11.60,11.30,11.10,10.80,10.60,10.40,10.10,9.92,9.70,9.50,9.30,9.11,8.92,8.74,8.56,8.39,8.22,8.05,7.89,7.74,7.59,7.45,7.31,7.17,7.04,6.92,6.79,6.68,6.56,6.45,6.34,6.23,6.13,6.02,5.92,5.83,5.73,5.64,5.55,5.46,5.38,5.29,5.21,5.14,5.06,4.99,4.92,4.85,4.78,4.72,4.66,4.66
191,Vietnam,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,417.0,416.0,416.0,415.0,415.0,414.0,413.0,413.0,412.0,411.0,410.0,409.0,408.0,407.0,406.0,405.0,404.0,403.0,402.0,401.0,400.0,399.0,398.0,397.0,396.0,395.0,394.0,393.0,392.0,391.0,391.0,384.0,378.0,371.0,364.0,359.0,352.0,334.0,315.0,299.0,281.0,266.0,250.0,236.0,222.0,208.0,195.0,183.0,171.0,160.0,151.0,148.0,142.0,136.0,130.0,125.0,120.0,115.0,110.0,105.0,101.0,96.8,92.8,89.0,85.5,84.8,84.1,83.6,83.0,82.3,81.6,80.8,79.9,78.8,77.6,76.2,74.7,73.2,71.5,69.8,68.2,66.7,65.3,63.9,62.6,61.2,59.7,58.0,56.0,53.7,51.4,48.9,46.40,43.90,41.40,39.10,36.90,34.90,33.00,31.40,29.90,28.60,27.50,26.60,25.80,25.10,24.50,24.10,23.70,23.40,23.10,22.80,22.60,22.30,22.10,21.80,21.50,21.10,20.70,20.40,20.00,19.70,19.40,19.00,18.60,18.30,17.90,17.50,17.10,16.60,16.20,15.80,15.50,15.10,14.80,14.50,14.20,13.90,13.70,13.50,13.20,13.00,12.70,12.50,12.30,12.10,11.90,11.70,11.50,11.30,11.10,10.90,10.70,10.50,10.40,10.20,10.00,9.87,9.71,9.56,9.41,9.27,9.13,8.99,8.86,8.74,8.62,8.50,8.38,8.27,8.16,8.05,7.95,7.85,7.75,7.66,7.57,7.48,7.39,7.31,7.23,7.15,7.07,6.99,6.91,6.84,6.76,6.69,6.62,6.55,6.48,6.41,6.35,6.28,6.22,6.16,6.10,6.04,5.98,5.92,5.92
192,Yemen,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,540.0,539.0,539.0,538.0,538.0,537.0,536.0,535.0,534.0,533.0,532.0,531.0,530.0,528.0,527.0,526.0,525.0,523.0,522.0,521.0,520.0,518.0,517.0,516.0,514.0,513.0,512.0,511.0,509.0,508.0,507.0,506.0,502.0,498.0,495.0,491.0,488.0,484.0,481.0,477.0,474.0,470.0,467.0,464.0,460.0,457.0,453.0,450.0,447.0,443.0,440.0,437.0,436.0,434.0,432.0,430.0,429.0,427.0,425.0,423.0,421.0,418.0,414.0,409.0,402.0,394.0,385.0,375.0,364.0,352.0,339.0,327.0,315.0,304.0,293.0,282.0,271.0,259.0,246.0,233.0,221.0,208.0,195.0,184.0,172.0,162.0,154.0,146.0,140.0,135.0,130.0,126.0,122.0,119.00,116.00,114.00,112.00,109.00,107.00,103.00,99.30,94.90,90.30,85.60,81.10,76.70,72.50,68.40,64.60,61.00,58.00,56.00,55.10,55.00,55.00,55.00,55.00,55.00,55.00,55.00,54.90,54.60,54.10,53.50,52.80,52.00,51.00,49.90,48.60,47.20,45.80,44.30,42.90,41.60,40.40,39.40,38.50,37.70,37.00,36.30,35.60,34.90,34.20,33.60,32.90,32.30,31.60,31.00,30.50,29.90,29.30,28.80,28.30,27.80,27.30,26.80,26.40,25.90,25.50,25.00,24.60,24.20,23.80,23.30,22.90,22.50,22.20,21.80,21.40,21.10,20.70,20.40,20.00,19.70,19.40,19.00,18.70,18.40,18.10,17.80,17.50,17.20,16.90,16.70,16.40,16.10,15.80,15.60,15.30,15.00,14.80,14.50,14.30,14.10,13.80,13.60,13.40,13.20,13.00,12.80,12.60,12.60
193,Zambia,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,410.0,409.0,409.0,409.0,409.0,408.0,408.0,407.0,407.0,406.0,405.0,404.0,403.0,403.0,402.0,401.0,400.0,399.0,398.0,397.0,396.0,395.0,394.0,393.0,392.0,391.0,390.0,389.0,388.0,387.0,386.0,385.0,384.0,383.0,381.0,378.0,376.0,374.0,371.0,369.0,366.0,364.0,362.0,359.0,357.0,355.0,352.0,350.0,330.0,312.0,294.0,277.0,262.0,247.0,245.0,240.0,236.0,231.0,226.0,223.0,219.0,214.0,210.0,206.0,202.0,198.0,195.0,192.0,190.0,189.0,188.0,186.0,184.0,181.0,176.0,170.0,165.0,160.0,156.0,154.0,154.0,155.0,156.0,156.0,157.0,158.0,161.0,164.0,169.0,174.0,178.0,181.0,184.0,186.0,187.0,187.00,186.00,184.00,181.00,178.00,175.00,173.00,169.00,162.00,153.00,142.00,130.00,119.00,110.00,101.00,95.40,90.40,85.10,80.30,77.20,74.30,70.70,66.90,64.60,62.00,59.40,57.80,56.10,54.50,53.00,51.50,50.10,48.80,47.50,46.20,45.00,43.80,42.60,41.50,40.40,39.30,38.20,37.20,36.20,35.30,34.30,33.40,32.60,31.70,30.90,30.10,29.40,28.60,27.90,27.20,26.60,25.90,25.30,24.70,24.10,23.60,23.00,22.50,22.00,21.60,21.10,20.70,20.30,19.90,19.50,19.10,18.80,18.40,18.10,17.80,17.40,17.10,16.90,16.60,16.30,16.00,15.80,15.60,15.30,15.10,14.90,14.70,14.50,14.30,14.10,13.90,13.70,13.50,13.30,13.20,13.00,12.90,12.70,12.60,12.50,12.30,12.20,12.10,11.90,11.80,11.70,11.60,11.40,11.40

In [77]:
#removing years outside our dataframe
df06 = df06.drop(df06.columns.to_series()["1800":"1989"], axis=1)
df06 = df06.drop(df06.columns.to_series()["2018":], axis=1)

In [78]:
df06 = df06.applymap(lambda s:s.lower() if type(s) == str else s) #lowercasing

In [79]:
df06 = pd.melt(df06,id_vars=["country"], var_name="year", value_name="child_mort").sort_values(["country", "year"], ascending = [True, True], ignore_index=True)

In [80]:
df06

          country  year  child_mort
0     afghanistan  1990       179.0
1     afghanistan  1991       173.0
2     afghanistan  1992       167.0
3     afghanistan  1993       161.0
4     afghanistan  1994       156.0
...           ...   ...         ...
5455     zimbabwe  2013        62.3
5456     zimbabwe  2014        57.5
5457     zimbabwe  2015        54.3
5458     zimbabwe  2016        50.4
5459     zimbabwe  2017        49.3

[5460 rows x 3 columns]

In [81]:
#now let's move on to health indicators: hiv, tb, malaria

In [82]:
df07 = pd.read_csv("data/gap_minder/gap_minder_newly_hiv_infected_percent_age_15_49.csv")
df08 = pd.read_csv("data/gap_minder/gap_minder_all_forms_of_tb_new_cases_per_100000_estimated.csv")
df09 = pd.read_csv("data/gap_minder/gap_minder_malaria_cases_per_100000_reported.csv")

In [83]:
#all datasets fall within our timeframe

In [84]:
#lowercasing
df07 = df07.applymap(lambda s:s.lower() if type(s) == str else s)
df08 = df08.applymap(lambda s:s.lower() if type(s) == str else s)
df09 = df09.applymap(lambda s:s.lower() if type(s) == str else s)

In [85]:
#pivoting
df07 = pd.melt(df07,id_vars=["country"], var_name="year", value_name="hiv_infect").sort_values(["country", "year"], ascending = [True, True], ignore_index=True)
df08 = pd.melt(df08,id_vars=["country"], var_name="year", value_name="tb_prev").sort_values(["country", "year"], ascending = [True, True], ignore_index=True)
df09 = pd.melt(df09,id_vars=["country"], var_name="year", value_name="ml_prev").sort_values(["country", "year"], ascending = [True, True], ignore_index=True)

In [86]:
df07

          country  year  hiv_infect
0     afghanistan  1990      0.0006
1     afghanistan  1991         NaN
2     afghanistan  1992         NaN
3     afghanistan  1993         NaN
4     afghanistan  1994         NaN
...           ...   ...         ...
3141     zimbabwe  2007      0.0144
3142     zimbabwe  2008      0.0144
3143     zimbabwe  2009      0.0136
3144     zimbabwe  2010      0.0125
3145     zimbabwe  2011      0.0105

[3146 rows x 3 columns]

In [87]:
df08

          country  year  tb_prev
0     afghanistan  1990    168.0
1     afghanistan  1991    168.0
2     afghanistan  1992    168.0
3     afghanistan  1993    168.0
4     afghanistan  1994    168.0
...           ...   ...      ...
3415     zimbabwe  2003    825.0
3416     zimbabwe  2004    834.0
3417     zimbabwe  2005    824.0
3418     zimbabwe  2006    803.0
3419     zimbabwe  2007    782.0

[3420 rows x 3 columns]

In [88]:
df09

          country  year  ml_prev
0     afghanistan  1990   2510.0
1     afghanistan  1991   2200.0
2     afghanistan  1992      NaN
3     afghanistan  1993      NaN
4     afghanistan  1994    512.0
...           ...   ...      ...
1797     zimbabwe  2002  10500.0
1798     zimbabwe  2003  14100.0
1799     zimbabwe  2004  13900.0
1800     zimbabwe  2005  11400.0
1801     zimbabwe  2006  11600.0

[1802 rows x 3 columns]

# Merging dataframes

In [89]:
#before we do a join of any sort, let's check that all the countries from the "smaller" dataframes are included in the countries from the biggest dataframe

In [90]:
df_list = [df00, df01, df02, df03, df04, df05, df06, df07, df08, df09] #define list of our dataframes
dict_countries = { i : df_list[i]["country"].nunique() for i in range(0, len(df_list)) } #finding the df that has the highesdt number of distinct countries

In [91]:
dict_countries

{0: 187,
 1: 195,
 2: 191,
 3: 194,
 4: 194,
 5: 192,
 6: 195,
 7: 143,
 8: 190,
 9: 106}

In [92]:
#the above tells us that we should use our list df01 as a reference for our left joins, as there is a high likelyhood that it contains all other countries from other dataframes
#we also know that this dataframe has the biggest timeframe (because we will also be joining on year). So let's use df01 as the base for our joins

In [93]:
df_tot = pd.merge(df01,df00,"left",on = ["country","year"])

In [94]:
df_tot

          country  year  total_pop  life_exp
0     afghanistan  1990   12400000      52.6
1     afghanistan  1991   13300000      52.4
2     afghanistan  1992   14500000      52.9
3     afghanistan  1993   15800000      53.1
4     afghanistan  1994   17100000      52.7
...           ...   ...        ...       ...
5455     zimbabwe  2013   13400000      56.8
5456     zimbabwe  2014   13600000      58.5
5457     zimbabwe  2015   13800000      59.6
5458     zimbabwe  2016   14000000      60.5
5459     zimbabwe  2017   14200000      61.4

[5460 rows x 4 columns]

In [95]:
df_tot["life_exp"].isna().sum() - df00["life_exp"].isna().sum()

224

In [96]:
#looks good, the null values we have introduced in df_tot are equal to the delta between the sizes of df01 and df00 => or left join is working!

In [97]:
#let's try to join all the rest in one shot:
for i in [2, len(df_list)-2]: #starting from df02
    df_tot = pd.merge(df_tot, df_list[i],"left",on = ["country","year"])

In [98]:
df_tot

          country  year  total_pop  life_exp  gdp_cap  tb_prev
0     afghanistan  1990   12400000      52.6      NaN    168.0
1     afghanistan  1991   13300000      52.4      NaN    168.0
2     afghanistan  1992   14500000      52.9      NaN    168.0
3     afghanistan  1993   15800000      53.1      NaN    168.0
4     afghanistan  1994   17100000      52.7      NaN    168.0
...           ...   ...        ...       ...      ...      ...
5455     zimbabwe  2013   13400000      56.8   1230.0      NaN
5456     zimbabwe  2014   13600000      58.5   1230.0      NaN
5457     zimbabwe  2015   13800000      59.6   1230.0      NaN
5458     zimbabwe  2016   14000000      60.5   1220.0      NaN
5459     zimbabwe  2017   14200000      61.4   1260.0      NaN

[5460 rows x 6 columns]

In [99]:
#clearly, this isn't working, let's make sure all the data types are correct
df_tot = pd.merge(df01,df00,"left",on = ["country","year"]) #go back to our initial df_tot

In [100]:
dict_datatypes = { i : [df_list[i]["country"].dtype, df_list[i]["year"].dtype] for i in range(0, len(df_list)) }
dict_datatypes

{0: [dtype('O'), dtype('O')],
 1: [dtype('O'), dtype('O')],
 2: [dtype('O'), dtype('O')],
 3: [dtype('O'), dtype('O')],
 4: [dtype('O'), dtype('O')],
 5: [dtype('O'), dtype('O')],
 6: [dtype('O'), dtype('O')],
 7: [dtype('O'), dtype('O')],
 8: [dtype('O'), dtype('O')],
 9: [dtype('O'), dtype('O')]}

In [101]:
df_list[0]["country"].dtype

dtype('O')

In [102]:
#one explanation why we're messing up our joins is that there could be white spaces, let's strip everything:
for i in range(0, len(df_list)):
    df_list[i]["country"] = df_list[i]["country"].str.strip()
    df_list[i]["year"] = df_list[i]["year"].str.strip()
#now let's try to merge again

In [103]:
df_tot = pd.merge(df01,df00,"left",on = ["country","year"])
for i in [2, len(df_list)-1]: #starting from df02
    df_tot = pd.merge(df_tot, df_list[i],"left",on = ["country","year"])

In [104]:
df_tot

          country  year  total_pop  life_exp  gdp_cap  ml_prev
0     afghanistan  1990   12400000      52.6      NaN   2510.0
1     afghanistan  1991   13300000      52.4      NaN   2200.0
2     afghanistan  1992   14500000      52.9      NaN      NaN
3     afghanistan  1993   15800000      53.1      NaN      NaN
4     afghanistan  1994   17100000      52.7      NaN    512.0
...           ...   ...        ...       ...      ...      ...
5455     zimbabwe  2013   13400000      56.8   1230.0      NaN
5456     zimbabwe  2014   13600000      58.5   1230.0      NaN
5457     zimbabwe  2015   13800000      59.6   1230.0      NaN
5458     zimbabwe  2016   14000000      60.5   1220.0      NaN
5459     zimbabwe  2017   14200000      61.4   1260.0      NaN

[5460 rows x 6 columns]

In [105]:
# still not working. Interestingly, it is only adding the first and last columns of my iterable. 
# this is possibly an indication that something is wrong with this kind of for loop in python. 
# before we do everything manually, let's try the reduce function, which seems particularly well-adapted for this situation

In [106]:
from functools import reduce #importing

In [107]:
df_list_bis = [df01, df00, df02, df03, df04, df05, df06, df07, df08, df09] #putting my df01 first 
df_tot = reduce((lambda x, y: pd.merge(x, y,"left",on = ["country","year"])), df_list_bis)

In [108]:
df_tot

,country,year,total_pop,life_exp,gdp_cap,sanit_access,water_access,dr_per_1000,child_mort,hiv_infect,tb_prev,ml_prev
0,afghanistan,1990,12400000,52.6,NaN,NaN,NaN,0.1090,179.0,0.0006,168.0,2510.0
1,afghanistan,1991,13300000,52.4,NaN,NaN,NaN,NaN,173.0,NaN,168.0,2200.0
2,afghanistan,1992,14500000,52.9,NaN,NaN,NaN,NaN,167.0,NaN,168.0,NaN
3,afghanistan,1993,15800000,53.1,NaN,NaN,NaN,0.1430,161.0,NaN,168.0,NaN
4,afghanistan,1994,17100000,52.7,NaN,NaN,NaN,NaN,156.0,NaN,168.0,512.0
...,...,...,...,...,...,...,...,...,...,...,...,...
5455,zimbabwe,2013,13400000,56.8,1230.0,0.389,0.660,0.0834,62.3,NaN,NaN,NaN
5456,zimbabwe,2014,13600000,58.5,1230.0,0.383,0.655,0.1240,57.5,NaN,NaN,NaN
5457,zimbabwe,2015,13800000,59.6,1230.0,0.376,0.650,0.1810,54.3,NaN,NaN,NaN
5458,zimbabwe,2016,14000000,60.5,1220.0,0.369,0.645,0.1790,50.4,NaN,NaN,NaN
5459,zimbabwe,2017,14200000,61.4,1260.0,0.362,0.641,0.1860,49.3,NaN,NaN,NaN

In [109]:
#YAAASS!

In [110]:
#let's analyse this dataframe with pandas profiling
df_tot.profile_report()

HBox(children=(FloatProgress(value=0.0, description='Summarize dataset', max=26.0, style=ProgressStyle(descrip…

HBox(children=(FloatProgress(value=0.0, description='Generate report structure', max=1.0, style=ProgressStyle(…

In [123]:
#we've got some serious null values there.

# First run of the model, quick and dirty

In [124]:
#let's drop all rows containing null values
df_tot_0 = df_tot.dropna(how="any",axis=0)

In [125]:
df_tot_0.size

1944

In [126]:
#we lost way too much data, let's still try and run the model

In [127]:
#importing models we will run:
from sklearn.model_selection import train_test_split as tts #import train_test_split

from sklearn.linear_model import LinearRegression as LinReg #import linear regression

from sklearn.linear_model import Lasso # import regularization 1/3      
from sklearn.linear_model import Ridge # import regularization 2/3      
from sklearn.linear_model import ElasticNet # import regularization 3/3

from sklearn.ensemble import RandomForestRegressor as RFR #import random forest regressor

In [128]:
#importing model evaluation tools:
from sklearn.metrics import mean_squared_error as mse #MSE
from sklearn.metrics import mean_absolute_error as mae #MAE

In [129]:
#let's define a function that runs all our models. This will happen after we do the train-test split

def run_models(a,b,c,d): #a,b,c,d sont respectivement X_train, y_train, X_test, y_test
    
    model_names=["linreg", "lasso", "ridge", "elastic", "rfr"] #this will become the first column of our dataframe
    Res = pd.DataFrame({"model":[0,0,0,0,0], "R2":[0,0,0,0,0], "R2A":[0,0,0,0,0], "MSE":[0,0,0,0,0], "RMSE":[0,0,0,0,0], "MAE":[0,0,0,0,0]})#initializing "results" dataframe
    Res["model"] = model_names #filling the first columns
    
    #Running the models:
    #linreg
    linreg=LinReg()    
    linreg.fit(a, b)   
    y_pred_linreg=linreg.predict(c)
    #lasso
    lasso=Lasso()
    lasso.fit(a, b)
    y_pred_lasso=lasso.predict(c)
    #ridge
    ridge=Ridge()
    ridge.fit(a, b)
    y_pred_ridge=ridge.predict(c)
    #elasticnet
    elastic=ElasticNet()
    elastic.fit(a, b)
    y_pred_elastic=elastic.predict(c)
    #random forst regressor
    rfr=RFR()
    rfr.fit(a, b)
    y_pred_rfr=rfr.predict(c)
    
    #defining 2 lists that will be our iterables for completing the Res dataframe:
    models=[linreg, lasso, ridge, elastic, rfr]
    preds=[y_pred_linreg, y_pred_lasso, y_pred_ridge, y_pred_elastic, y_pred_rfr]
    
    #for loop to fill out the dataframe
    for i in range(len(models)):
        Res.loc[i,"R2"] = round(models[i].score(c, d),2)
        Res.loc[i,"R2A"] = round(1 - (1-models[i].score(c, d))*(len(d)-1)/(len(d)-c.shape[1]-1),2) #R2 adjusted
        Res.loc[i,"MSE"] = round(mse(preds[i], d),2)
        Res.loc[i,"RMSE"] = round(mse(preds[i], d)**0.5,2)
        Res.loc[i,"MAE"] = round(mae(preds[i], d),2)
        
    return Res

In [130]:
df_tot_0.columns

Index(['country', 'year', 'total_pop', 'life_exp', 'gdp_cap', 'sanit_access',
       'water_access', 'dr_per_1000', 'child_mort', 'hiv_infect', 'tb_prev',
       'ml_prev'],
      dtype='object')

In [131]:
X=df_tot_0[["gdp_cap", "sanit_access",
       "water_access", "dr_per_1000", "child_mort", "hiv_infect", "tb_prev",
       "ml_prev"]] #removed country, year, total_pop because they're useless; also removed "life_exp" obviously
y=df_tot_0["life_exp"]

In [132]:
X_train, X_test, y_train, y_test=tts(X, y, test_size=0.2, random_state=40) #test size 20%

In [133]:
run_models(X_train, y_train, X_test, y_test)

     model    R2   R2A    MSE  RMSE   MAE
0   linreg  0.90  0.87   8.11  2.85  2.07
1    lasso  0.90  0.87   8.29  2.88  1.99
2    ridge  0.91  0.88   7.69  2.77  2.00
3  elastic  0.90  0.87   8.30  2.88  1.99
4      rfr  0.77  0.70  18.57  4.31  2.41

In [135]:
#regression
import statsmodels.api as sm
lin_reg = sm.OLS(y, X)
results = lin_reg.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:               life_exp   R-squared (uncentered):                   0.984
Model:                            OLS   Adj. R-squared (uncentered):              0.984
Method:                 Least Squares   F-statistic:                              1209.
Date:                Wed, 16 Dec 2020   Prob (F-statistic):                   8.49e-135
Time:                        18:37:40   Log-Likelihood:                         -565.88
No. Observations:                 162   AIC:                                      1148.
Df Residuals:                     154   BIC:                                      1172.
Df Model:                           8
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
gdp_cap          0.0009      0.000      2.399      0.018       0.000       0.002
sanit_access    19.5081      3.702      5.269      0.000      12.195      26.822
water_access    52.3457      3.487     15.013      0.000      45.458      59.233
dr_per_1000      0.2630      0.910      0.289      0.773      -1.534       2.060
child_mort       0.1831      0.016     11.586      0.000       0.152       0.214
hiv_infect    -662.1293    151.887     -4.359      0.000    -962.180    -362.078
tb_prev          0.0026      0.006      0.430      0.668      -0.009       0.014
ml_prev       7.473e-05   7.37e-05      1.014      0.312   -7.09e-05       0.000
==============================================================================
Omnibus:                        3.977   Durbin-Watson:                   0.831
Prob(Omnibus):                  0.137   Jarque-Bera (JB):                3.511
Skew:                           0.300   Prob(JB):                        0.173
Kurtosis:                       3.400   Cond. No.                     2.75e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.75e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

As we see from the above, removing all those rows containing nulls his led to some high p-values, namely for tb and ml prevalence 
With the exception of the number doctors per 1000 inhabitants and tuberculosis & measles prevalence, the overall model that we built is relatively accurate and the data statistically significant

# Let's check if we can import other datasets and add other columns

In [273]:
#let's import the GINI coefficient table, which measures inequality in a society
df10 = pd.read_csv("data/gap_minder/gap_minder_gini.csv")

In [274]:
#removing years outside our dataframe
df10 = df10.drop(df10.columns.to_series()["1800":"1989"], axis=1)
df10 = df10.drop(df10.columns.to_series()["2018":], axis=1)

In [275]:
df10 = df10.applymap(lambda s:s.lower() if type(s) == str else s) #lowercasing

In [276]:
df10 = pd.melt(df10,id_vars=["country"], var_name="year", value_name="gini").sort_values(["country", "year"], ascending = [True, True], ignore_index=True)

In [277]:
df10.head()

       country  year  gini
0  afghanistan  1990  36.4
1  afghanistan  1991  36.7
2  afghanistan  1992  36.7
3  afghanistan  1993  36.8
4  afghanistan  1994  36.8

In [279]:
df_tot = pd.merge(df_tot, df10,"left",on = ["country","year"])

In [280]:
#let's drop our null values again and run the model
df_tot_0 = df_tot.dropna(how="any",axis=0)

In [281]:
X=df_tot_0[["gdp_cap", "sanit_access",
       "water_access", "dr_per_1000", "child_mort", "hiv_infect", "tb_prev",
       "ml_prev", "gini"]] #removed country, year, total_pop because they're useless; also removed "life_exp" obviously
y=df_tot_0["life_exp"]

In [282]:
X_train, X_test, y_train, y_test=tts(X, y, test_size=0.2, random_state=40) #test size 20%

In [283]:
run_models(X_train, y_train, X_test, y_test)

     model    R2   R2A    MSE  RMSE   MAE
0   linreg  0.90  0.86   8.42  2.90  2.09
1    lasso  0.90  0.86   8.29  2.88  1.99
2    ridge  0.91  0.87   7.77  2.79  2.01
3  elastic  0.90  0.86   8.30  2.88  1.99
4      rfr  0.78  0.70  17.80  4.22  2.46

In [284]:
#gini is bad for our model, let's remove it again 
df_tot = df_tot.drop(columns = ["gini"])

In [285]:
df_tot.head()

,country,year,total_pop,life_exp,gdp_cap,sanit_access,water_access,dr_per_1000,child_mort,hiv_infect,tb_prev,ml_prev
0,afghanistan,1990,12400000,52.6,NaN,NaN,NaN,0.109,179.0,0.0006,168.0,2510.0
1,afghanistan,1991,13300000,52.4,NaN,NaN,NaN,NaN,173.0,NaN,168.0,2200.0
2,afghanistan,1992,14500000,52.9,NaN,NaN,NaN,NaN,167.0,NaN,168.0,NaN
3,afghanistan,1993,15800000,53.1,NaN,NaN,NaN,0.143,161.0,NaN,168.0,NaN
4,afghanistan,1994,17100000,52.7,NaN,NaN,NaN,NaN,156.0,NaN,168.0,512.0

In [289]:
df_tot.shape

(5460, 12)

In [290]:
#let's bring in other possibly relevant datasets
ls data/gap_minder

SyntaxError: invalid syntax (<ipython-input-290-7b4fb70f8ebe>, line 2)

In [291]:
ls data/gap_minder

countries+countrycode/
gap_minder_all_forms_of_tb_new_cases_per_100000_estimated.csv
gap_minder_at_least_basic_sanitation_overall_access_percent.csv
gap_minder_at_least_basic_water_source_overall_access_percent.csv
gap_minder_child_mortality_0_5_year_olds_dying_per_1000_born.csv
gap_minder_food_supply_kilocalories_per_person_and_day.csv
gap_minder_gdppercapita_us_inflation_adjusted.csv
gap_minder_gini.csv
gap_minder_government_share_of_total_health_spending_percent.csv
gap_minder_life_expectancy_at_birth_data_from_ihme.csv
gap_minder_life_expectancy_years.csv
gap_minder_malaria_cases_per_100000_reported.csv
gap_minder_medical_doctors_per_1000_people.csv
gap_minder_newly_hiv_infected_percent_age_15_49.csv
gap_minder_population_total.csv

In [292]:
df11 = pd.read_csv("data/gap_minder/gap_minder_government_share_of_total_health_spending_percent.csv")#share of health spending covered by the governmen (%)
df12 = pd.read_csv("data/gap_minder/gap_minder_food_supply_kilocalories_per_person_and_day.csv") #kilocalories available per day per person

In [293]:
#removing years outside our dataframe
df12 = df12.drop(df12.columns.to_series()["1961":"1989"], axis=1) #all the rest is included in our timeframe

In [294]:
df11 = df11.applymap(lambda s:s.lower() if type(s) == str else s) #lowercasing
df12 = df12.applymap(lambda s:s.lower() if type(s) == str else s) #lowercasing

In [295]:
#pivoting
df11 = pd.melt(df11,id_vars=["country"], var_name="year", value_name="public_health").sort_values(["country", "year"], ascending = [True, True], ignore_index=True) 
df12 = pd.melt(df12,id_vars=["country"], var_name="year", value_name="cals_available").sort_values(["country", "year"], ascending = [True, True], ignore_index=True)

In [296]:
df_tot = pd.merge(df_tot, df11,"left",on = ["country","year"]) #appending

In [297]:
df_tot = pd.merge(df_tot, df12,"left",on = ["country","year"]) #appending

In [298]:
df_tot.head()

,country,year,total_pop,life_exp,gdp_cap,sanit_access,water_access,dr_per_1000,child_mort,hiv_infect,tb_prev,ml_prev,public_health,cals_available
0,afghanistan,1990,12400000,52.6,NaN,NaN,NaN,0.109,179.0,0.0006,168.0,2510.0,NaN,2310.0
1,afghanistan,1991,13300000,52.4,NaN,NaN,NaN,NaN,173.0,NaN,168.0,2200.0,NaN,2040.0
2,afghanistan,1992,14500000,52.9,NaN,NaN,NaN,NaN,167.0,NaN,168.0,NaN,NaN,1890.0
3,afghanistan,1993,15800000,53.1,NaN,NaN,NaN,0.143,161.0,NaN,168.0,NaN,NaN,1910.0
4,afghanistan,1994,17100000,52.7,NaN,NaN,NaN,NaN,156.0,NaN,168.0,512.0,NaN,1820.0

In [302]:
df_tot.shape

(5460, 14)

In [305]:
df_tot.isna().sum()

country              0
year                 0
total_pop            0
life_exp           224
gdp_cap            349
sanit_access      2021
water_access      2011
dr_per_1000       2324
child_mort           0
hiv_infect        3914
tb_prev           2056
ml_prev           3863
public_health     2452
cals_available    1527
dtype: int64

In [299]:
#let's drop our null values again and run the model
df_tot_0 = df_tot.dropna(how="any",axis=0)

In [300]:
df_tot_0.shape

(155, 14)

In [306]:
df11.isna().sum()

country           0
year              0
public_health    32
dtype: int64